<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv('train_data.csv')
test = pd.read_csv('test_data.csv')
validation = pd.read_csv('validation_data.csv')

In [3]:
train.head()

  CategoryCode  ItemCode      DateID  DailySales
0   category_2    117610   11/6/2021           7
1   category_4    836584  11/18/2021          16
2   category_1    370195   1/24/2022           6
3   category_2    172582  10/30/2021           5
4   category_2   1006009  10/30/2021           5

In [4]:
test.head()

  CategoryCode  ItemCode Week  PredictedSales
0   category_1     43738   w4             NaN
1   category_2   1006090   w1             NaN
2   category_2   1076929   w4             NaN
3   category_1   1081321   w3             NaN
4   category_2    216151   w4             NaN

In [5]:
validation.head()

  CategoryCode  ItemCode Week  WeeklySales
0   category_2   1044502   w1           11
1   category_2   1105009   w1           11
2   category_2    913561   w4            5
3   category_1   1048975   w4           30
4   category_1     17287   w2           60

In [6]:
val_ItemCode = validation.ItemCode.unique()
test_ItemCode = test.ItemCode.unique()

In [7]:
np.array_equal([1,2,3], [1,2,3])

True

In [8]:
np.array_equal(val_ItemCode, test_ItemCode)

False

In [9]:
val_ItemCode

array([1044502, 1105009,  913561, 1048975,   17287,  371239, 1098502,
       1074823,   23569,  397213,  211309, 1058713, 1032550, 1071106,
         40759, 1067092, 1101661,  210868,  379249,   75886, 1044682,
       1090303, 1084498, 1064473, 1030948, 1090276,  138742,   24136,
        836125,   64978, 1032541,  865933,  836152,  839356,  906586,
         30877,  173617, 1006108, 1064572,  416212,   35584, 1070836,
         43657,  110320,    3427,  877624, 1090105,  248272,  124954,
       1097143, 1098493,  745945,   48940,   86974, 1076938,   59047,
        172582, 1044619, 1013335, 1015621, 1047130,  132028, 1010068,
       1066570, 1076920, 1071124,  172033,  399220,  142756, 1006009,
       1003156, 1090294,   99079, 1050046, 1026871,   59749,  118033,
          3418,  124774, 1003147,    7666,  245581, 1081087, 1061638,
         17296, 1090240,   76399,  131983,   50785,  755584,  267496,
         20824, 1060909, 1090114, 1032586], dtype=int64)

In [10]:
list1 = [1,2,3,4,5,6]
list2 = [3, 5, 7, 9]
list(set(val_ItemCode.tolist()).intersection(test_ItemCode.tolist()))

[]

In [11]:
train.shape, test.shape, validation.shape

((19921, 4), (377, 4), (370, 4))

In [12]:
train.dtypes

CategoryCode    object
ItemCode         int64
DateID          object
DailySales       int64
dtype: object

In [13]:
validation.dtypes

CategoryCode    object
ItemCode         int64
Week            object
WeeklySales      int64
dtype: object

In [14]:
train['Day'] = train['DateID'].str.split('/').str[1]
train['Month'] = train['DateID'].str.split('/').str[0]

In [15]:
train['Day'] = train['Day'].astype(int)
train['Month'] = train['Month'].astype(int)

In [89]:
train[train['ItemCode']== 1061341].sort_values(by='DateID').tail(20)

      CategoryCode  ItemCode      DateID  DailySales  Day  Month Week
4007    category_1   1061341  2021-12-25           2   25     12  w12
15339   category_1   1061341  2021-12-27           3   27     12  w13
18591   category_1   1061341  2021-12-28           2   28     12  w13
6538    category_1   1061341  2021-12-29           8   29     12  w13
4772    category_1   1061341  2021-12-30           4   30     12  w13
11564   category_1   1061341  2021-12-31           4   31     12  w13
11981   category_1   1061341  2022-01-01           6    1      1  w13
11253   category_1   1061341  2022-01-02          10    2      1  w13
7632    category_1   1061341  2022-01-11           7   11      1  w15
12725   category_1   1061341  2022-01-12           2   12      1  w15
5751    category_1   1061341  2022-01-13           3   13      1  w15
14776   category_1   1061341  2022-01-20           1   20      1  w16
6281    category_1   1061341  2022-01-21           1   21      1  w16
4148    category_1   1061341  2022-01-22           8   22      1  w16
3308    category_1   1061341  2022-01-23           7   23      1  w16
7       category_1   1061341  2022-01-24           5   24      1  w17
6815    category_1   1061341  2022-01-25           1   25      1  w17
4173    category_1   1061341  2022-01-29          11   29      1  w17
18647   category_1   1061341  2022-01-31           2   31      1  w18
12956   category_1   1061341  2022-02-01           6    1      2  w18

In [17]:
train.head()

  CategoryCode  ItemCode      DateID  DailySales  Day  Month
0   category_2    117610   11/6/2021           7    6     11
1   category_4    836584  11/18/2021          16   18     11
2   category_1    370195   1/24/2022           6   24      1
3   category_2    172582  10/30/2021           5   30     10
4   category_2   1006009  10/30/2021           5   30     10

In [18]:
train.dtypes

CategoryCode    object
ItemCode         int64
DateID          object
DailySales       int64
Day              int32
Month            int32
dtype: object

In [19]:
14 <= 17 <= 20

True

In [20]:
train['DateID'] = pd.to_datetime(train['DateID']).dt.date

In [21]:
from datetime import date
def week_cal(x):
    if date(2021, 10, 4) <= x <= date(2021, 10, 10):
        return "w01"
    elif date(2021, 10, 11) <= x <= date(2021, 10, 17):
        return "w02"
    elif date(2021, 10, 18) <= x <= date(2021, 10, 24):
        return "w03"
    elif date(2021, 10, 25) <= x <= date(2021, 10, 31):
        return "w04"
    elif date(2021, 11, 1) <= x <= date(2021, 11, 7):
        return "w05"
    elif date(2021, 11, 8) <= x <= date(2021, 11, 14):
        return "w06"
    elif date(2021, 11, 15) <= x <= date(2021, 11, 21):
        return "w07"
    elif date(2021, 11, 22) <= x <= date(2021, 11, 28):
        return "w08"
    elif date(2021, 11, 29) <= x <= date(2021, 12, 5):
        return "w09"
    elif date(2021, 12, 6) <= x <= date(2021, 12, 12):
        return "w10"
    elif date(2021, 12, 13) <= x <= date(2021, 12, 19):
        return "w11"
    elif date(2021, 12, 20) <= x <= date(2021, 12, 26):
        return "w12"
    elif date(2021, 12, 27) <= x <= date(2022, 1, 2):
        return "w13"
    elif date(2022, 1, 3) <= x <= date(2021, 1, 9):
        return "w14"
    elif date(2022, 1, 10) <= x <= date(2022, 1, 16):
        return "w15"
    elif date(2022, 1, 17) <= x <= date(2022, 1, 23):
        return "w16"
    elif date(2022, 1, 24) <= x <= date(2022, 1, 30):
        return "w17"
    elif date(2022, 1, 31) <= x <= date(2022, 2, 6):
        return "w18"
    elif date(2022, 2, 7) <= x <= date(2022, 2, 13):
        return "w19"
    else:                                                       # 28 <= x or x <= 6
        return 'Omit'
    # Add elif statements....

train['Week'] = train['DateID'].apply(week_cal)

In [22]:
train = train[train.Week != 'Omit']

In [23]:
sorted_train = train.sort_values(by=['ItemCode', 'DateID'], ascending=True)
sorted_train

      CategoryCode  ItemCode      DateID  DailySales  Day  Month Week
8593    category_1      3418  2021-10-04           2    4     10  w01
18463   category_1      3418  2021-10-05           4    5     10  w01
18053   category_1      3418  2021-10-06           2    6     10  w01
19019   category_1      3418  2021-10-07           8    7     10  w01
2076    category_1      3418  2021-10-08          12    8     10  w01
...            ...       ...         ...         ...  ...    ...  ...
1095    category_2   1105027  2022-02-09           5    9      2  w19
5970    category_2   1105027  2022-02-10           1   10      2  w19
6781    category_2   1105027  2022-02-11           2   11      2  w19
14672   category_2   1105027  2022-02-12           2   12      2  w19
10029   category_2   1105027  2022-02-13           3   13      2  w19

[18427 rows x 7 columns]

In [24]:
# sorted_train.groupby(['ItemCode', 'DateID'])['Week', 'DailySales'].apply(lambda x : x.astype(int).sum())

In [25]:
week_sale_grouped_train = sorted_train.groupby(['ItemCode','Week'])['DailySales'].sum()
week_sale_grouped_train.head(30)

ItemCode  Week
3418      w01      42
          w02      41
          w03      41
          w04      44
          w05      46
          w06      43
          w07      49
          w08      54
          w09      69
          w10     101
          w11      73
          w12      75
          w13      56
          w15      85
          w16      89
          w17      67
          w18     109
          w19      72
3427      w01      40
          w02      20
          w03      48
          w04      54
          w05      28
          w06      36
          w07      52
          w08      42
          w09      57
          w10      46
          w11      45
          w12      78
Name: DailySales, dtype: int64

In [26]:
merged_train = pd.merge(train[['DateID','CategoryCode','ItemCode','Month','Day','Week']], week_sale_grouped_train, on=['ItemCode','Week'], how='left')
merged_train.sort_values(by=['ItemCode', 'Week'], ascending=True).head()

           DateID CategoryCode  ItemCode  Month  Day Week  DailySales
1625   2021-10-08   category_1      3418     10    8  w01          42
7848   2021-10-04   category_1      3418     10    4  w01          42
8319   2021-10-10   category_1      3418     10   10  w01          42
16657  2021-10-06   category_1      3418     10    6  w01          42
17067  2021-10-05   category_1      3418     10    5  w01          42

In [27]:
# merged_train = merged_train.sort_values(by=['Week', 'CategoryCode', 'ItemCode'], ascending=False).drop_duplicates(subset=['CategoryCode','ItemCode', 'DateID'])
merged_train = merged_train.drop_duplicates(subset=['CategoryCode','ItemCode', 'Week'])

In [28]:
merged_train.rename(columns={'DailySales':'WeeklySales'}, inplace=True)

In [29]:
merged_train

           DateID CategoryCode  ItemCode  Month  Day Week  WeeklySales
0      2021-11-06   category_2    117610     11    6  w05           65
1      2021-11-18   category_4    836584     11   18  w07          123
2      2022-01-24   category_1    370195      1   24  w17           37
3      2021-10-30   category_2    172582     10   30  w04           26
4      2021-10-30   category_2   1006009     10   30  w04           13
...           ...          ...       ...    ...  ...  ...          ...
17824  2021-11-04   category_3      7666     11    4  w05           15
18003  2021-11-19   category_1     37510     11   19  w07            3
18188  2021-10-18   category_2     57058     10   18  w03            4
18217  2021-10-19   category_2   1006108     10   19  w03            2
18239  2021-10-18   category_1   1068883     10   18  w03            1

[3401 rows x 7 columns]

In [30]:
week_start_date = merged_train['Week'].replace({'w01':'2021-10-04','w02': '2021-10-11','w03':'2021-10-18',
                                                'w04':'2021-10-25','w05':'2021-11-01','w06':'2021-11-08',
                                                'w07':'2021-11-15','w08':'2021-11-22','w09':'2021-11-29',
                                                'w10':'2021-12-6','w11':'2021-12-13','w12':'2021-12-20',
                                                'w13':'2021-12-27','w14':'2022-01-03','w15':'2022-01-10',
                                                'w16':'2022-01-17','w17':'2022-01-24',
                                                'w18':'2022-01-31','w19':'2022-02-07'})

In [31]:
merged_train['DateID'] = week_start_date
merged_train['DateID'] = pd.to_datetime(merged_train['DateID']).dt.date

In [32]:
merged_train

           DateID CategoryCode  ItemCode  Month  Day Week  WeeklySales
0      2021-11-01   category_2    117610     11    6  w05           65
1      2021-11-15   category_4    836584     11   18  w07          123
2      2022-01-24   category_1    370195      1   24  w17           37
3      2021-10-25   category_2    172582     10   30  w04           26
4      2021-10-25   category_2   1006009     10   30  w04           13
...           ...          ...       ...    ...  ...  ...          ...
17824  2021-11-01   category_3      7666     11    4  w05           15
18003  2021-11-15   category_1     37510     11   19  w07            3
18188  2021-10-18   category_2     57058     10   18  w03            4
18217  2021-10-18   category_2   1006108     10   19  w03            2
18239  2021-10-18   category_1   1068883     10   18  w03            1

[3401 rows x 7 columns]

In [33]:
# week_start_date = merged_train['Week'].replace({'w01':date(2021, 10, 4),'w02':date(2021, 10, 11),'w03':(2021, 10, 18),
#                                                 'w04':date(2021, 10, 25),'w05':date(2021, 11, 1),'w06':(2021, 11, 8),
#                                                 'w07':(2021, 11, 15),'w08':(2021, 11, 22),'w09':(2021, 11, 29),
#                                                 'w10':date(2021, 12, 6),'w11':date(2021, 12, 13),'w12':date(2021, 12, 20),
#                                                 'w13':date(2021, 12, 27),'w14':date(2022, 1, 3),'w15':date(2022, 1, 10),
#                                                 'w16':date(2022, 1, 17),'w17':date(2022, 1, 24),
#                                                 'w18':date(2022, 1, 31),'w19':date(2022, 2, 7)})
# week_start_date

In [34]:
sorted_merged_train = merged_train.sort_values(by=['Week', 'CategoryCode', 'ItemCode'], ascending=True)
sorted_merged_train.head(30)

           DateID CategoryCode  ItemCode  Month  Day Week  WeeklySales
1625   2021-10-04   category_1      3418     10    8  w01           42
2168   2021-10-04   category_1      3427     10    8  w01           40
2473   2021-10-04   category_1     17287     10    8  w01           16
1552   2021-10-04   category_1     17296     10    8  w01          274
7963   2021-10-04   category_1     24136     10    4  w01           25
2581   2021-10-04   category_1     35449     10    8  w01            1
2085   2021-10-04   category_1     35530     10    8  w01           21
16893  2021-10-04   category_1     35584     10    6  w01            6
2217   2021-10-04   category_1     36898     10    8  w01           55
15834  2021-10-04   category_1     37510     10    9  w01           12
2546   2021-10-04   category_1     38518     10    8  w01           25
2460   2021-10-04   category_1     42424     10    8  w01           24
8406   2021-10-04   category_1     42496     10   10  w01           11
2392   2021-10-04   category_1     43657     10    8  w01           12
7879   2021-10-04   category_1     43738     10    4  w01           11
16792  2021-10-04   category_1     48940     10    6  w01           10
16108  2021-10-04   category_1     59047     10    9  w01            5
2377   2021-10-04   category_1     76399     10    8  w01           11
1717   2021-10-04   category_1     86992     10    8  w01           43
1914   2021-10-04   category_1    119554     10    8  w01          108
1786   2021-10-04   category_1    124774     10    8  w01           26
1758   2021-10-04   category_1    142756     10    8  w01           43
1723   2021-10-04   category_1    145330     10    8  w01           11
2084   2021-10-04   category_1    145978     10    8  w01           35
1979   2021-10-04   category_1    370195     10    8  w01           35
17713  2021-10-04   category_1    371104     10    7  w01            6
8218   2021-10-04   category_1    371239     10   10  w01           10
2342   2021-10-04   category_1    379249     10    8  w01           26
17118  2021-10-04   category_1    416212     10    5  w01            4
2221   2021-10-04   category_1    755584     10    8  w01           31

In [35]:
# sorted_merged_train.to_csv('F:/merged_train.csv', index=False)

In [36]:
merged_train[merged_train['ItemCode'] == 3418].shape

(18, 7)

In [37]:
len(train.ItemCode.value_counts().index.tolist())

194

In [38]:
len(merged_train.ItemCode.value_counts().index.tolist())

194

In [39]:
train_for_test = merged_train.loc[merged_train['ItemCode'].isin(test.ItemCode.value_counts().index.tolist())]

In [40]:
tr_te_itemcodes = pd.DataFrame()
tr_te_itemcodes['TrainItemCode'] = np.sort(train_for_test['ItemCode'].unique())
tr_te_itemcodes['ValItemCode'] = np.sort(test['ItemCode'].unique())
tr_te_itemcodes.sort_values(by='TrainItemCode')

    TrainItemCode  ValItemCode
0            9925         9925
1           16936        16936
2           23200        23200
3           32245        32245
4           35449        35449
..            ...          ...
92        1101571      1101571
93        1101769      1101769
94        1103056      1103056
95        1105018      1105018
96        1105027      1105027

[97 rows x 2 columns]

In [41]:
len(train_for_test.ItemCode.value_counts().index.tolist())

97

In [42]:
len(test.ItemCode.value_counts().index.tolist())

97

In [43]:
train_for_test.shape

(1699, 7)

In [44]:
merged_train.shape

(3401, 7)

In [45]:
train.shape[0]/18

1023.7222222222222

In [46]:
train_for_test.head()

       DateID CategoryCode  ItemCode  Month  Day Week  WeeklySales
0  2021-11-01   category_2    117610     11    6  w05           65
2  2022-01-24   category_1    370195      1   24  w17           37
5  2021-10-25   category_1    145978     10   30  w04           31
6  2022-01-24   category_1   1061341      1   24  w17           17
8  2021-12-06   category_1   1061341     12    7  w10           40

In [47]:
train_for_test['WeeklySales'].max()

808

In [48]:
test.head()

  CategoryCode  ItemCode Week  PredictedSales
0   category_1     43738   w4             NaN
1   category_2   1006090   w1             NaN
2   category_2   1076929   w4             NaN
3   category_1   1081321   w3             NaN
4   category_2    216151   w4             NaN

In [49]:
train['DateID'] = pd.to_datetime(train['DateID']).dt.date

In [50]:
test_date = test['Week'].replace(['w1', 'w2', 'w3', 'w4'], ['2022-02-14', '2022-02-21', '2022-02-28', '2022-03-07'])

In [51]:
test['DateID'] = test_date

In [52]:
test['DateID'] = pd.to_datetime(test['DateID']).dt.date

In [53]:
test.head()

  CategoryCode  ItemCode Week  PredictedSales      DateID
0   category_1     43738   w4             NaN  2022-03-07
1   category_2   1006090   w1             NaN  2022-02-14
2   category_2   1076929   w4             NaN  2022-03-07
3   category_1   1081321   w3             NaN  2022-02-28
4   category_2    216151   w4             NaN  2022-03-07

In [54]:
train_for_test.head()

       DateID CategoryCode  ItemCode  Month  Day Week  WeeklySales
0  2021-11-01   category_2    117610     11    6  w05           65
2  2022-01-24   category_1    370195      1   24  w17           37
5  2021-10-25   category_1    145978     10   30  w04           31
6  2022-01-24   category_1   1061341      1   24  w17           17
8  2021-12-06   category_1   1061341     12    7  w10           40

In [55]:
train_test_merged = pd.concat((train_for_test[['DateID','CategoryCode','ItemCode','WeeklySales']], test[['DateID','CategoryCode','ItemCode', 'PredictedSales']]))

In [56]:
train_test_merged.head()

       DateID CategoryCode  ItemCode  WeeklySales  PredictedSales
0  2021-11-01   category_2    117610         65.0             NaN
2  2022-01-24   category_1    370195         37.0             NaN
5  2021-10-25   category_1    145978         31.0             NaN
6  2022-01-24   category_1   1061341         17.0             NaN
8  2021-12-06   category_1   1061341         40.0             NaN

In [57]:
train_test_merged.drop(columns='PredictedSales', inplace=True)

In [58]:
train_test_merged

         DateID CategoryCode  ItemCode  WeeklySales
0    2021-11-01   category_2    117610         65.0
2    2022-01-24   category_1    370195         37.0
5    2021-10-25   category_1    145978         31.0
6    2022-01-24   category_1   1061341         17.0
8    2021-12-06   category_1   1061341         40.0
..          ...          ...       ...          ...
372  2022-02-14   category_2   1101571          NaN
373  2022-03-07   category_2   1090258          NaN
374  2022-02-14   category_2    906595          NaN
375  2022-02-14   category_2     32245          NaN
376  2022-02-21   category_2   1006090          NaN

[2076 rows x 4 columns]

In [59]:
from keras.preprocessing import sequence
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout, Flatten, AveragePooling1D

from keras.optimizers import Adam
from keras.models import load_model
from keras.callbacks import ModelCheckpoint

def get_model(shape1, shape2):
    model = Sequential()
    model.add(LSTM(6, batch_input_shape=(1, shape1, shape2), stateful=True))
    model.add(Dense(1))
    model.compile(loss='mean_absolute_percentage_error', optimizer='adam')
    return model

Using TensorFlow backend.

In [60]:
df_prediction = pd.DataFrame(columns=['CategoryCode', 'ItemCode', 'Week', 'PredictedSales'])
i = 0
def week_cal(df, item_code, cat_code):
    print('week cal running')
    global i
    global df_prediction
    CategoryCode = cat_code
    ItemCode = item_code
    w1 = df['pred_value'].iloc[0]
    w2 = df['pred_value'].iloc[1]
    w3 = df['pred_value'].iloc[2]
    w4 = df['pred_value'].iloc[3]
#     print('CategoryCode',CategoryCode, 'ItemCode',ItemCode, 'Week','w1', 'PredictedSales',w1)
    df_prediction.loc[i] = [CategoryCode] +  [ItemCode] + ['w1'] + [w1]
    i = i+1
    df_prediction.loc[i] = [CategoryCode] +  [ItemCode] + ['w2'] + [w2]
    i = i+1
    df_prediction.loc[i] = [CategoryCode] +  [ItemCode] + ['w3'] + [w3]
    i = i+1
    df_prediction.loc[i] = [CategoryCode] +  [ItemCode] + ['w4'] + [w4]
    i = i+1
#     print(df_prediction)

In [61]:
# df_prediction

In [62]:
# train_test_merged[train_test_merged['ItemCode'] == 1061341].sort_values(by='DateID')

In [63]:
#import MinMaxScaler and create a new dataframe for LSTM model
from sklearn.preprocessing import MinMaxScaler

def predict(item, item_code, cat_code):
    item = item.drop(columns=['CategoryCode','ItemCode'])
    item = item.sort_values(by='DateID', ascending=True).reset_index(drop=True)
    item = item.fillna(item['WeeklySales'].min())
    print(item)
    #create a new dataframe to model the difference
    df_diff = item.copy()
    #add previous sales to the next row
    df_diff['prev_sales'] = df_diff['WeeklySales'].shift(1)
    #drop the null values and calculate the difference
    df_diff = df_diff.dropna()
    df_diff['diff'] = (df_diff['WeeklySales'] - df_diff['prev_sales'])
    df_diff
    
    #create dataframe for transformation from time series to supervised
    df_supervised = df_diff.drop(['prev_sales'],axis=1)
    #adding lags
    for inc in range(1,10):
        field_name = 'lag_' + str(inc)
        df_supervised[field_name] = df_supervised['diff'].shift(inc)
    #drop null values
    df_supervised = df_supervised.dropna().reset_index(drop=True)
    
    #MinMaxScaler and create a new dataframe for LSTM model
    df_model = df_supervised.drop(['DateID'],axis=1)
    #split train and test set
    train_set, test_set = df_model.iloc[0:-4].values, df_model.iloc[-4:].values
    
    #apply Min Max Scaler
    scaler = MinMaxScaler(feature_range=(-1, 1))
    scaler = scaler.fit(train_set)
    # reshape training set
    train_set = train_set.reshape(train_set.shape[0], train_set.shape[1])
    train_set_scaled = scaler.transform(train_set)
    # reshape test set
    test_set = test_set.reshape(test_set.shape[0], test_set.shape[1])
    test_set_scaled = scaler.transform(test_set)
    
    X_train, y_train = train_set_scaled[:, 1:], train_set_scaled[:, 0:1]
    X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
    X_test, y_test = test_set_scaled[:, 1:], test_set_scaled[:, 0:1]
    X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])
#     print(y_test)
    #get model
    model = get_model(X_train.shape[1], X_train.shape[2])
    model.fit(X_train, y_train, nb_epoch=100, batch_size=1, verbose=0, shuffle=False)
    
    y_pred = model.predict(X_test,batch_size=1)
    #for multistep prediction, you need to replace X_test values with the predictions coming from t-1
    
    #reshape y_pred
    y_pred = y_pred.reshape(y_pred.shape[0], 1, y_pred.shape[1])
    #rebuild test set for inverse transform
    pred_test_set = []
    for index in range(0,len(y_pred)):
#         print (np.concatenate([y_pred[index],X_test[index]],axis=1))
        pred_test_set.append(np.concatenate([y_pred[index],X_test[index]],axis=1))
    #reshape pred_test_set
    pred_test_set = np.array(pred_test_set)
    pred_test_set = pred_test_set.reshape(pred_test_set.shape[0], pred_test_set.shape[2])
    #inverse transform
    pred_test_set_inverted = scaler.inverse_transform(pred_test_set)
    
    #create dataframe that shows the predicted sales
    result_list = []
    sales_dates = list(item[-5:].DateID)
    act_sales = list(item[-5:].WeeklySales)
    for index in range(0,len(pred_test_set_inverted)):
        result_dict = {}
        result_dict['pred_value'] = int(pred_test_set_inverted[index][0] + act_sales[index])
        result_dict['DateID'] = sales_dates[index+1]
        result_list.append(result_dict)
    df_result = pd.DataFrame(result_list)
    #for multistep prediction, replace act_sales with the predicted sales
#     print(df_result)
    week_cal(df_result, item_code, cat_code)

In [64]:
# train_test_merged.ItemCode.unique()

In [65]:
for itemcode in train_test_merged.ItemCode.unique():
    print(itemcode)
    item_df = train_test_merged[train_test_merged['ItemCode'] == itemcode].sort_values(by=['DateID'], ascending=True)
    cat_code = item_df['CategoryCode'].unique()[0]
    
    # item_df['yhat_lower'] = item_df['DailySales'] - 1
    # item_df['yhat_upper'] = item_df['DailySales'] + 1
    #     print(item_df)
    df = predict(item_df, itemcode, cat_code)

117610
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11         11.0
2   2021-10-18         14.0
3   2021-10-25         27.0
4   2021-11-01         65.0
5   2021-11-08         29.0
6   2021-11-15         21.0
7   2021-11-22         26.0
8   2021-11-29          7.0
9   2021-12-06          4.0
10  2021-12-13         28.0
11  2021-12-20          8.0
12  2021-12-27         11.0
13  2022-01-10         11.0
14  2022-01-17          6.0
15  2022-01-24          7.0
16  2022-01-31         10.0
17  2022-02-07          7.0
18  2022-02-14          4.0
19  2022-02-21          4.0
20  2022-02-28          4.0
21  2022-03-07          4.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
370195
        DateID  WeeklySales
0   2021-10-04         35.0
1   2021-10-11         26.0
2   2021-10-18         48.0
3   2021-10-25         41.0
4   2021-11-01         44.0
5   2021-11-08         63.0
6   2021-11-15         20.0
7   2021-11-22         48.0
8   2021-11-29         56.0
9   2021-12-06         90.0
10  2021-12-13         47.0
11  2021-12-20         96.0
12  2021-12-27         67.0
13  2022-01-10         34.0
14  2022-01-17         29.0
15  2022-01-24         37.0
16  2022-01-31         56.0
17  2022-02-07         52.0
18  2022-02-14         20.0
19  2022-02-21         20.0
20  2022-02-28         20.0
21  2022-03-07         20.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
145978
        DateID  WeeklySales
0   2021-10-04         35.0
1   2021-10-11         32.0
2   2021-10-18         34.0
3   2021-10-25         31.0
4   2021-11-01         27.0
5   2021-11-08         23.0
6   2021-11-15         30.0
7   2021-11-22         44.0
8   2021-11-29         49.0
9   2021-12-06         31.0
10  2021-12-13         56.0
11  2021-12-20         46.0
12  2021-12-27         38.0
13  2022-01-10         32.0
14  2022-01-17         41.0
15  2022-01-24         51.0
16  2022-01-31         33.0
17  2022-02-07         32.0
18  2022-02-14         23.0
19  2022-02-21         23.0
20  2022-02-28         23.0
21  2022-03-07         23.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1061341
        DateID  WeeklySales
0   2021-10-04         62.0
1   2021-10-11         44.0
2   2021-10-18         54.0
3   2021-10-25         25.0
4   2021-11-01         72.0
5   2021-11-08         50.0
6   2021-11-15         29.0
7   2021-11-22         45.0
8   2021-11-29         29.0
9   2021-12-06         40.0
10  2021-12-13         43.0
11  2021-12-20         67.0
12  2021-12-27         37.0
13  2022-01-10         12.0
14  2022-01-17         17.0
15  2022-01-24         17.0
16  2022-01-31          8.0
17  2022-02-14          8.0
18  2022-02-21          8.0
19  2022-02-28          8.0
20  2022-03-07          8.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1054978
        DateID  WeeklySales
0   2021-10-04         60.0
1   2021-10-11         77.0
2   2021-10-18         63.0
3   2021-10-25         38.0
4   2021-11-01         62.0
5   2021-11-08         39.0
6   2021-11-15         41.0
7   2021-11-22         75.0
8   2021-11-29         42.0
9   2021-12-06         49.0
10  2021-12-13         42.0
11  2021-12-20         34.0
12  2021-12-27         25.0
13  2022-01-10         72.0
14  2022-01-17         51.0
15  2022-01-24         54.0
16  2022-01-31         60.0
17  2022-02-07         48.0
18  2022-02-14         25.0
19  2022-02-21         25.0
20  2022-02-28         25.0
21  2022-03-07         25.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1044610
        DateID  WeeklySales
0   2021-10-04          6.0
1   2021-10-11         13.0
2   2021-10-18          8.0
3   2021-10-25         13.0
4   2021-11-01          8.0
5   2021-11-08          3.0
6   2021-11-15          6.0
7   2021-11-22         14.0
8   2021-11-29         12.0
9   2021-12-06         14.0
10  2021-12-13         24.0
11  2021-12-20         12.0
12  2021-12-27         24.0
13  2022-01-10         17.0
14  2022-01-17         13.0
15  2022-01-24          5.0
16  2022-01-31         10.0
17  2022-02-07          4.0
18  2022-02-14          3.0
19  2022-02-21          3.0
20  2022-02-28          3.0
21  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
815101
        DateID  WeeklySales
0   2021-10-04         26.0
1   2021-10-11         21.0
2   2021-10-18         31.0
3   2021-10-25         31.0
4   2021-11-01         18.0
5   2021-11-08         22.0
6   2021-11-15         21.0
7   2021-11-22         40.0
8   2021-11-29         25.0
9   2021-12-06         44.0
10  2021-12-13         39.0
11  2021-12-20         32.0
12  2021-12-27         25.0
13  2022-01-10         21.0
14  2022-01-17         30.0
15  2022-01-24         31.0
16  2022-01-31         16.0
17  2022-02-07         21.0
18  2022-02-14         16.0
19  2022-02-21         16.0
20  2022-02-28         16.0
21  2022-03-07         16.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
39436
        DateID  WeeklySales
0   2021-10-04        161.0
1   2021-10-11         93.0
2   2021-10-18         26.0
3   2021-10-25         22.0
4   2021-11-01         15.0
5   2021-11-08         21.0
6   2021-11-15         10.0
7   2021-11-22         10.0
8   2021-11-29         11.0
9   2021-12-06         10.0
10  2021-12-13         22.0
11  2021-12-20         16.0
12  2021-12-27         15.0
13  2022-01-10         14.0
14  2022-01-17         22.0
15  2022-01-24         21.0
16  2022-01-31         18.0
17  2022-02-07         23.0
18  2022-02-14         10.0
19  2022-02-21         10.0
20  2022-02-28         10.0
21  2022-03-07         10.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1103056
        DateID  WeeklySales
0   2021-10-11          8.0
1   2021-10-18         12.0
2   2021-10-25         28.0
3   2021-11-01         27.0
4   2021-11-08         20.0
5   2021-11-15         17.0
6   2021-11-22         24.0
7   2021-11-29         19.0
8   2021-12-06         12.0
9   2021-12-13          7.0
10  2021-12-20         18.0
11  2021-12-27         14.0
12  2022-01-10         16.0
13  2022-01-17         15.0
14  2022-01-24         13.0
15  2022-01-31         18.0
16  2022-02-07         10.0
17  2022-02-14          7.0
18  2022-02-21          7.0
19  2022-02-28          7.0
20  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1044691
        DateID  WeeklySales
0   2021-10-04         13.0
1   2021-10-11         16.0
2   2021-10-18         11.0
3   2021-10-25         20.0
4   2021-11-01         13.0
5   2021-11-08         12.0
6   2021-11-15         22.0
7   2021-11-22         28.0
8   2021-11-29         27.0
9   2021-12-06         23.0
10  2021-12-13         15.0
11  2021-12-20          8.0
12  2021-12-27         22.0
13  2022-01-10         25.0
14  2022-01-17         17.0
15  2022-01-24         12.0
16  2022-01-31         23.0
17  2022-02-07         23.0
18  2022-02-14          8.0
19  2022-02-21          8.0
20  2022-02-28          8.0
21  2022-03-07          8.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1090024
        DateID  WeeklySales
0   2021-10-04         22.0
1   2021-10-11         13.0
2   2021-10-18         24.0
3   2021-10-25         17.0
4   2021-11-01         14.0
5   2021-11-08         10.0
6   2021-11-15         20.0
7   2021-11-22         21.0
8   2021-11-29         10.0
9   2021-12-06         14.0
10  2021-12-13         13.0
11  2021-12-20          9.0
12  2021-12-27          8.0
13  2022-01-10         29.0
14  2022-01-17         17.0
15  2022-01-24         33.0
16  2022-01-31         46.0
17  2022-02-07         64.0
18  2022-02-14          8.0
19  2022-02-21          8.0
20  2022-02-28          8.0
21  2022-03-07          8.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1067074
        DateID  WeeklySales
0   2021-10-04         38.0
1   2021-10-11         27.0
2   2021-10-18         39.0
3   2021-10-25         29.0
4   2021-11-01         32.0
5   2021-11-08         34.0
6   2021-11-15         81.0
7   2021-11-22         22.0
8   2021-11-29         29.0
9   2021-12-06         31.0
10  2021-12-13         36.0
11  2021-12-20         30.0
12  2021-12-27         28.0
13  2022-01-10         26.0
14  2022-01-17         10.0
15  2022-01-24         48.0
16  2022-01-31         38.0
17  2022-02-07         74.0
18  2022-02-14         10.0
19  2022-02-21         10.0
20  2022-02-28         10.0
21  2022-03-07         10.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1021264
        DateID  WeeklySales
0   2021-10-04          9.0
1   2021-10-11         13.0
2   2021-10-18          5.0
3   2021-10-25          6.0
4   2021-11-01         10.0
5   2021-11-08          5.0
6   2021-11-15         14.0
7   2021-11-22          8.0
8   2021-11-29          9.0
9   2021-12-06         24.0
10  2021-12-13         22.0
11  2021-12-20          1.0
12  2021-12-27         45.0
13  2022-01-10          8.0
14  2022-01-17         21.0
15  2022-01-24         11.0
16  2022-01-31         17.0
17  2022-02-07          7.0
18  2022-02-14          1.0
19  2022-02-21          1.0
20  2022-02-28          1.0
21  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
839374
        DateID  WeeklySales
0   2021-10-04         13.0
1   2021-10-11         25.0
2   2021-10-18         13.0
3   2021-10-25         78.0
4   2021-11-01         38.0
5   2021-11-08         19.0
6   2021-11-15         14.0
7   2021-11-22         37.0
8   2021-11-29         28.0
9   2021-12-06         20.0
10  2021-12-13         50.0
11  2021-12-20         27.0
12  2021-12-27         57.0
13  2022-01-10         55.0
14  2022-01-17         48.0
15  2022-01-24         35.0
16  2022-01-31         47.0
17  2022-02-07         63.0
18  2022-02-14         13.0
19  2022-02-21         13.0
20  2022-02-28         13.0
21  2022-03-07         13.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1003192
        DateID  WeeklySales
0   2021-10-04         14.0
1   2021-10-11         22.0
2   2021-10-18          5.0
3   2021-10-25          8.0
4   2021-11-01          8.0
5   2021-11-08         25.0
6   2021-11-15         24.0
7   2021-11-22         24.0
8   2021-11-29         26.0
9   2021-12-06         11.0
10  2021-12-13         16.0
11  2021-12-20         34.0
12  2021-12-27         28.0
13  2022-01-10         42.0
14  2022-01-17         47.0
15  2022-01-24         48.0
16  2022-01-31         32.0
17  2022-02-07         77.0
18  2022-02-14          5.0
19  2022-02-21          5.0
20  2022-02-28          5.0
21  2022-03-07          5.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
174436
        DateID  WeeklySales
0   2021-10-04         64.0
1   2021-10-11         60.0
2   2021-10-18         69.0
3   2021-10-25         85.0
4   2021-11-01         62.0
5   2021-11-08         73.0
6   2021-11-15         47.0
7   2021-11-22         90.0
8   2021-11-29         63.0
9   2021-12-06         45.0
10  2021-12-13         51.0
11  2021-12-20         41.0
12  2021-12-27         37.0
13  2022-01-10         45.0
14  2022-01-17         45.0
15  2022-01-24         62.0
16  2022-01-31         61.0
17  2022-02-07         47.0
18  2022-02-14         37.0
19  2022-02-21         37.0
20  2022-02-28         37.0
21  2022-03-07         37.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
838456
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11         13.0
2   2021-10-18          8.0
3   2021-10-25         16.0
4   2021-11-01         11.0
5   2021-11-08         13.0
6   2021-11-15         18.0
7   2021-11-22         17.0
8   2021-11-29         21.0
9   2021-12-06         18.0
10  2021-12-13         18.0
11  2021-12-20         24.0
12  2021-12-27         25.0
13  2022-01-10         23.0
14  2022-01-17         17.0
15  2022-01-24         13.0
16  2022-01-31         14.0
17  2022-02-07         13.0
18  2022-02-14          8.0
19  2022-02-21          8.0
20  2022-02-28          8.0
21  2022-03-07          8.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
43630
        DateID  WeeklySales
0   2021-10-04         31.0
1   2021-10-11         20.0
2   2021-10-18         21.0
3   2021-10-25         33.0
4   2021-11-01         24.0
5   2021-11-08         31.0
6   2021-11-15         25.0
7   2021-11-22         27.0
8   2021-11-29         29.0
9   2021-12-06         39.0
10  2021-12-13         22.0
11  2021-12-20         22.0
12  2021-12-27         21.0
13  2022-01-10         22.0
14  2022-01-17         36.0
15  2022-01-24         52.0
16  2022-01-31         25.0
17  2022-02-07         49.0
18  2022-02-14         20.0
19  2022-02-21         20.0
20  2022-02-28         20.0
21  2022-03-07         20.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
262384
        DateID  WeeklySales
0   2021-10-04          9.0
1   2021-10-11          7.0
2   2021-10-18         13.0
3   2021-10-25         14.0
4   2021-11-01         19.0
5   2021-11-08          7.0
6   2021-11-15         15.0
7   2021-11-22         17.0
8   2021-11-29         17.0
9   2021-12-06         16.0
10  2021-12-13         19.0
11  2021-12-20         18.0
12  2021-12-27         21.0
13  2022-01-10         20.0
14  2022-01-17         14.0
15  2022-01-24         13.0
16  2022-01-31         17.0
17  2022-02-07         16.0
18  2022-02-14          7.0
19  2022-02-21          7.0
20  2022-02-28          7.0
21  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
36898
        DateID  WeeklySales
0   2021-10-04         55.0
1   2021-10-11         40.0
2   2021-10-18         90.0
3   2021-10-25         82.0
4   2021-11-01         74.0
5   2021-11-08         58.0
6   2021-11-15         70.0
7   2021-11-22         62.0
8   2021-11-29         85.0
9   2021-12-06         76.0
10  2021-12-13         60.0
11  2021-12-20         76.0
12  2021-12-27         75.0
13  2022-01-10         90.0
14  2022-01-17        118.0
15  2022-01-24         53.0
16  2022-01-31         77.0
17  2022-02-07         70.0
18  2022-02-14         40.0
19  2022-02-21         40.0
20  2022-02-28         40.0
21  2022-03-07         40.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1006090
        DateID  WeeklySales
0   2021-10-04          6.0
1   2021-10-11         14.0
2   2021-10-18          9.0
3   2021-10-25         14.0
4   2021-11-01         16.0
5   2021-11-08         16.0
6   2021-11-15         19.0
7   2021-11-22         12.0
8   2021-11-29         15.0
9   2021-12-06         19.0
10  2021-12-13         33.0
11  2021-12-20         19.0
12  2021-12-27         38.0
13  2022-01-10         19.0
14  2022-01-17         36.0
15  2022-01-24         29.0
16  2022-01-31         15.0
17  2022-02-07         21.0
18  2022-02-14          6.0
19  2022-02-21          6.0
20  2022-02-28          6.0
21  2022-03-07          6.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
87046
        DateID  WeeklySales
0   2021-10-04          6.0
1   2021-10-11          6.0
2   2021-10-18          1.0
3   2021-11-01         11.0
4   2021-11-08         15.0
5   2021-11-15          7.0
6   2021-11-22          5.0
7   2021-11-29          7.0
8   2021-12-06         17.0
9   2021-12-13         12.0
10  2021-12-20         17.0
11  2021-12-27         18.0
12  2022-01-10         13.0
13  2022-01-17         10.0
14  2022-02-14          1.0
15  2022-02-21          1.0
16  2022-02-28          1.0
17  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1024810
        DateID  WeeklySales
0   2021-10-04         59.0
1   2021-10-11         49.0
2   2021-10-18         34.0
3   2021-10-25         38.0
4   2021-11-01         66.0
5   2021-11-08         55.0
6   2021-11-15         50.0
7   2021-11-22         53.0
8   2021-11-29         75.0
9   2021-12-06         85.0
10  2021-12-13        113.0
11  2021-12-20        113.0
12  2021-12-27         96.0
13  2022-01-10         36.0
14  2022-01-24        121.0
15  2022-01-31         86.0
16  2022-02-07         21.0
17  2022-02-14         21.0
18  2022-02-21         21.0
19  2022-02-28         21.0
20  2022-03-07         21.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
130993
        DateID  WeeklySales
0   2021-10-04         19.0
1   2021-10-11          7.0
2   2021-10-18         13.0
3   2021-10-25          7.0
4   2021-11-01         43.0
5   2021-11-08         37.0
6   2021-11-15         41.0
7   2021-11-22          7.0
8   2021-11-29          7.0
9   2021-12-06         12.0
10  2021-12-13          5.0
11  2021-12-20         15.0
12  2021-12-27         29.0
13  2022-01-10         29.0
14  2022-01-17         25.0
15  2022-01-24         12.0
16  2022-01-31          6.0
17  2022-02-07         45.0
18  2022-02-14          5.0
19  2022-02-21          5.0
20  2022-02-28          5.0
21  2022-03-07          5.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
42424
        DateID  WeeklySales
0   2021-10-04         24.0
1   2021-10-11         33.0
2   2021-10-18         12.0
3   2021-10-25         22.0
4   2021-11-01         23.0
5   2021-11-08         27.0
6   2021-11-15         23.0
7   2021-11-22         28.0
8   2021-11-29         33.0
9   2021-12-06         58.0
10  2021-12-13         41.0
11  2021-12-20         62.0
12  2021-12-27         27.0
13  2022-01-10         61.0
14  2022-01-17         37.0
15  2022-01-24         41.0
16  2022-01-31         61.0
17  2022-02-07         59.0
18  2022-02-14         12.0
19  2022-02-21         12.0
20  2022-02-28         12.0
21  2022-03-07         12.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
123307
        DateID  WeeklySales
0   2021-10-04        569.0
1   2021-10-11        493.0
2   2021-10-18        378.0
3   2021-10-25        552.0
4   2021-11-01        330.0
5   2021-11-08        397.0
6   2021-11-15        332.0
7   2021-11-22        409.0
8   2021-11-29        400.0
9   2021-12-06        396.0
10  2021-12-13        516.0
11  2021-12-20        683.0
12  2021-12-27        731.0
13  2022-01-10        539.0
14  2022-01-17        527.0
15  2022-01-24        356.0
16  2022-01-31        376.0
17  2022-02-07        555.0
18  2022-02-14        330.0
19  2022-02-21        330.0
20  2022-02-28        330.0
21  2022-03-07        330.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
57058
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11          6.0
2   2021-10-18          4.0
3   2021-10-25          2.0
4   2021-11-01          5.0
5   2021-11-08         10.0
6   2021-11-15          4.0
7   2021-11-22          7.0
8   2021-11-29          3.0
9   2021-12-06         13.0
10  2021-12-13          4.0
11  2021-12-20          3.0
12  2021-12-27         13.0
13  2022-01-10          7.0
14  2022-01-17         16.0
15  2022-01-24         12.0
16  2022-01-31         12.0
17  2022-02-07          5.0
18  2022-02-14          2.0
19  2022-02-21          2.0
20  2022-02-28          2.0
21  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
32245
        DateID  WeeklySales
0   2021-10-04         41.0
1   2021-10-11         24.0
2   2021-10-18         45.0
3   2021-10-25         28.0
4   2021-11-01         27.0
5   2021-11-08         29.0
6   2021-11-15         40.0
7   2021-11-22         29.0
8   2021-11-29         46.0
9   2021-12-06         38.0
10  2021-12-13         18.0
11  2021-12-20         53.0
12  2021-12-27         29.0
13  2022-01-10         30.0
14  2022-01-17         51.0
15  2022-01-24         51.0
16  2022-01-31         51.0
17  2022-02-07         51.0
18  2022-02-14         18.0
19  2022-02-21         18.0
20  2022-02-28         18.0
21  2022-03-07         18.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
16936
        DateID  WeeklySales
0   2021-10-04         25.0
1   2021-10-11         40.0
2   2021-10-18         31.0
3   2021-10-25         21.0
4   2021-11-01         43.0
5   2021-11-08          7.0
6   2021-11-15         34.0
7   2021-11-22        151.0
8   2021-11-29         32.0
9   2021-12-06         28.0
10  2021-12-13         25.0
11  2021-12-20         49.0
12  2021-12-27         40.0
13  2022-01-10         66.0
14  2022-01-17         43.0
15  2022-01-24         66.0
16  2022-01-31         48.0
17  2022-02-07         71.0
18  2022-02-14          7.0
19  2022-02-21          7.0
20  2022-02-28          7.0
21  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
41830
        DateID  WeeklySales
0   2021-10-04         17.0
1   2021-10-11         15.0
2   2021-10-18         12.0
3   2021-10-25         20.0
4   2021-11-01          8.0
5   2021-11-08          7.0
6   2021-11-15         24.0
7   2021-11-22         28.0
8   2021-11-29         14.0
9   2021-12-06         13.0
10  2021-12-13         20.0
11  2021-12-20         17.0
12  2021-12-27         25.0
13  2022-01-10         14.0
14  2022-01-17         16.0
15  2022-01-24         15.0
16  2022-01-31         22.0
17  2022-02-07          9.0
18  2022-02-14          7.0
19  2022-02-21          7.0
20  2022-02-28          7.0
21  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1047967
        DateID  WeeklySales
0   2021-10-04        106.0
1   2021-10-11        118.0
2   2021-10-18        113.0
3   2021-10-25         82.0
4   2021-11-01         94.0
5   2021-11-08        130.0
6   2021-11-15        174.0
7   2021-11-22         87.0
8   2021-11-29        138.0
9   2021-12-06         86.0
10  2021-12-13         95.0
11  2021-12-20        114.0
12  2021-12-27         82.0
13  2022-01-10        171.0
14  2022-01-17         80.0
15  2022-01-24        102.0
16  2022-01-31        111.0
17  2022-02-07        104.0
18  2022-02-14         80.0
19  2022-02-21         80.0
20  2022-02-28         80.0
21  2022-03-07         80.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
837943
        DateID  WeeklySales
0   2021-10-04         85.0
1   2021-10-11         50.0
2   2021-10-18         80.0
3   2021-10-25        102.0
4   2021-11-01         89.0
5   2021-11-08         79.0
6   2021-11-15        107.0
7   2021-11-22        102.0
8   2021-11-29         94.0
9   2021-12-06         96.0
10  2021-12-13         84.0
11  2021-12-20         89.0
12  2021-12-27         88.0
13  2022-01-10         55.0
14  2022-01-17        112.0
15  2022-01-24         88.0
16  2022-01-31         95.0
17  2022-02-07         78.0
18  2022-02-14         50.0
19  2022-02-21         50.0
20  2022-02-28         50.0
21  2022-03-07         50.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
169504
        DateID  WeeklySales
0   2021-10-04        780.0
1   2021-10-11        511.0
2   2021-10-18        808.0
3   2021-10-25        685.0
4   2021-11-01        664.0
5   2021-11-08        686.0
6   2021-11-15        720.0
7   2021-11-22        676.0
8   2021-11-29        604.0
9   2021-12-06        697.0
10  2021-12-13        737.0
11  2021-12-20        534.0
12  2021-12-27        662.0
13  2022-01-10        507.0
14  2022-01-17        515.0
15  2022-01-24        689.0
16  2022-01-31        271.0
17  2022-02-07        371.0
18  2022-02-14        271.0
19  2022-02-21        271.0
20  2022-02-28        271.0
21  2022-03-07        271.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
753613
        DateID  WeeklySales
0   2021-10-04         32.0
1   2021-10-11         11.0
2   2021-10-18         12.0
3   2021-10-25         19.0
4   2021-11-01         40.0
5   2021-11-08         34.0
6   2021-11-15         10.0
7   2021-11-22         36.0
8   2021-11-29         32.0
9   2021-12-06          5.0
10  2021-12-13         25.0
11  2021-12-20         17.0
12  2021-12-27         36.0
13  2022-01-10         59.0
14  2022-01-17        121.0
15  2022-01-24        104.0
16  2022-01-31         36.0
17  2022-02-07        129.0
18  2022-02-14          5.0
19  2022-02-21          5.0
20  2022-02-28          5.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
371104
        DateID  WeeklySales
0   2021-10-04          6.0
1   2021-10-11          6.0
2   2021-10-18         12.0
3   2021-10-25         11.0
4   2021-11-01          4.0
5   2021-11-08          6.0
6   2021-11-15         11.0
7   2021-11-22          5.0
8   2021-11-29         24.0
9   2021-12-06          9.0
10  2021-12-13         23.0
11  2021-12-20          7.0
12  2021-12-27          4.0
13  2022-01-10         16.0
14  2022-01-17          8.0
15  2022-01-24          7.0
16  2022-01-31          6.0
17  2022-02-07         21.0
18  2022-02-14          4.0
19  2022-02-21          4.0
20  2022-02-28          4.0
21  2022-03-07          4.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
42496
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11         22.0
2   2021-10-18         22.0
3   2021-10-25         45.0
4   2021-11-01         22.0
5   2021-11-08         32.0
6   2021-11-15         24.0
7   2021-11-22         20.0
8   2021-11-29         38.0
9   2021-12-06        102.0
10  2021-12-13         29.0
11  2021-12-20         43.0
12  2021-12-27         47.0
13  2022-01-10         35.0
14  2022-01-17         37.0
15  2022-01-24         39.0
16  2022-01-31         42.0
17  2022-02-07         30.0
18  2022-02-14         11.0
19  2022-02-21         11.0
20  2022-02-28         11.0
21  2022-03-07         11.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1101769
        DateID  WeeklySales
0   2021-10-04          3.0
1   2021-10-25         18.0
2   2021-11-01         20.0
3   2021-11-08         22.0
4   2021-11-15         17.0
5   2021-11-22         14.0
6   2021-11-29          1.0
7   2021-12-13          2.0
8   2022-01-10          7.0
9   2022-01-17         20.0
10  2022-01-24         32.0
11  2022-01-31         20.0
12  2022-02-07         33.0
13  2022-02-14          1.0
14  2022-02-21          1.0
15  2022-02-28          1.0
16  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1090258
        DateID  WeeklySales
0   2021-10-04          6.0
1   2021-10-11          6.0
2   2021-10-18          5.0
3   2021-10-25         79.0
4   2021-11-01         44.0
5   2021-11-08          2.0
6   2021-11-15          4.0
7   2021-11-22          8.0
8   2021-11-29         92.0
9   2021-12-06         21.0
10  2021-12-13          1.0
11  2021-12-20          6.0
12  2021-12-27          7.0
13  2022-01-10         72.0
14  2022-01-17         38.0
15  2022-01-24         18.0
16  2022-01-31         19.0
17  2022-02-07         35.0
18  2022-02-14          1.0
19  2022-02-21          1.0
20  2022-02-28          1.0
21  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1056463
        DateID  WeeklySales
0   2021-10-04         21.0
1   2021-10-11         25.0
2   2021-10-18         37.0
3   2021-10-25         37.0
4   2021-11-01         63.0
5   2021-11-08         39.0
6   2021-11-15         29.0
7   2021-11-22         30.0
8   2021-11-29         66.0
9   2021-12-06         22.0
10  2021-12-13         38.0
11  2021-12-20         46.0
12  2021-12-27        118.0
13  2022-01-10         43.0
14  2022-01-17         57.0
15  2022-01-24         72.0
16  2022-01-31        116.0
17  2022-02-07         33.0
18  2022-02-14         21.0
19  2022-02-21         21.0
20  2022-02-28         21.0
21  2022-03-07         21.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
87559
        DateID  WeeklySales
0   2021-10-04         30.0
1   2021-10-11         11.0
2   2021-10-18         18.0
3   2021-10-25         21.0
4   2021-11-01         13.0
5   2021-11-08         14.0
6   2021-11-15         24.0
7   2021-11-22         14.0
8   2021-11-29         15.0
9   2021-12-06         15.0
10  2021-12-13         48.0
11  2021-12-20         34.0
12  2021-12-27         54.0
13  2022-01-10         31.0
14  2022-01-17         18.0
15  2022-01-24         31.0
16  2022-01-31         29.0
17  2022-02-07         30.0
18  2022-02-14         11.0
19  2022-02-21         11.0
20  2022-02-28         11.0
21  2022-03-07         11.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1032532
        DateID  WeeklySales
0   2021-10-04         53.0
1   2021-10-11         54.0
2   2021-10-18         70.0
3   2021-10-25         73.0
4   2021-11-01        138.0
5   2021-11-08        101.0
6   2021-11-15         73.0
7   2021-11-22         73.0
8   2021-11-29         74.0
9   2021-12-06        186.0
10  2021-12-13         89.0
11  2021-12-20        129.0
12  2021-12-27        103.0
13  2022-01-10         93.0
14  2022-01-17        159.0
15  2022-01-24        108.0
16  2022-01-31        163.0
17  2022-02-07        153.0
18  2022-02-14         53.0
19  2022-02-21         53.0
20  2022-02-28         53.0
21  2022-03-07         53.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1075651
        DateID  WeeklySales
0   2021-10-04          5.0
1   2021-10-11          2.0
2   2021-10-18          4.0
3   2021-10-25          4.0
4   2021-11-01          7.0
5   2021-11-08         13.0
6   2021-11-15          5.0
7   2021-11-22         11.0
8   2021-11-29         14.0
9   2021-12-06         15.0
10  2021-12-13         13.0
11  2021-12-20         23.0
12  2021-12-27         17.0
13  2022-01-10          6.0
14  2022-01-17          1.0
15  2022-01-24          7.0
16  2022-01-31         17.0
17  2022-02-07         18.0
18  2022-02-14          1.0
19  2022-02-21          1.0
20  2022-02-28          1.0
21  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
267478
        DateID  WeeklySales
0   2021-10-04         44.0
1   2021-10-11         23.0
2   2021-10-18          9.0
3   2021-10-25          4.0
4   2021-11-01         12.0
5   2021-11-08          5.0
6   2021-11-15          5.0
7   2021-11-22         13.0
8   2021-11-29         12.0
9   2021-12-20          5.0
10  2021-12-27         10.0
11  2022-01-10          9.0
12  2022-01-17          4.0
13  2022-01-24          6.0
14  2022-01-31         13.0
15  2022-02-07         11.0
16  2022-02-14          4.0
17  2022-02-21          4.0
18  2022-02-28          4.0
19  2022-03-07          4.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1067119
        DateID  WeeklySales
0   2021-10-04         27.0
1   2021-10-11         27.0
2   2021-10-18         23.0
3   2021-10-25         22.0
4   2021-11-01         42.0
5   2021-11-08         22.0
6   2021-11-15         14.0
7   2021-11-22         21.0
8   2021-11-29         17.0
9   2021-12-06         24.0
10  2021-12-13         12.0
11  2021-12-20         26.0
12  2021-12-27         24.0
13  2022-01-10         32.0
14  2022-01-17         30.0
15  2022-01-24         21.0
16  2022-01-31         31.0
17  2022-02-07         34.0
18  2022-02-14         12.0
19  2022-02-21         12.0
20  2022-02-28         12.0
21  2022-03-07         12.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
37510
        DateID  WeeklySales
0   2021-10-04         12.0
1   2021-10-11          6.0
2   2021-10-18          6.0
3   2021-10-25         10.0
4   2021-11-01         11.0
5   2021-11-08          7.0
6   2021-11-15          3.0
7   2021-11-22          2.0
8   2021-11-29          4.0
9   2021-12-06         12.0
10  2021-12-13          7.0
11  2021-12-20          4.0
12  2021-12-27          4.0
13  2022-01-10          7.0
14  2022-01-17          7.0
15  2022-01-24          6.0
16  2022-01-31          8.0
17  2022-02-07         11.0
18  2022-02-14          2.0
19  2022-02-21          2.0
20  2022-02-28          2.0
21  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
23200
        DateID  WeeklySales
0   2021-10-04          7.0
1   2021-10-11         33.0
2   2021-10-18          7.0
3   2021-10-25         64.0
4   2021-11-01         80.0
5   2021-11-08         61.0
6   2021-11-15         30.0
7   2021-11-22        108.0
8   2021-11-29        163.0
9   2021-12-06        195.0
10  2021-12-13        149.0
11  2021-12-20         73.0
12  2021-12-27         95.0
13  2022-02-07         22.0
14  2022-02-14          7.0
15  2022-02-28          7.0
16  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
86992
        DateID  WeeklySales
0   2021-10-04         43.0
1   2021-10-11         31.0
2   2021-10-18         37.0
3   2021-10-25         45.0
4   2021-11-01         41.0
5   2021-11-08         33.0
6   2021-11-15         61.0
7   2021-11-22         50.0
8   2021-11-29         43.0
9   2021-12-06         54.0
10  2021-12-13         65.0
11  2021-12-20         55.0
12  2021-12-27         71.0
13  2022-01-10         52.0
14  2022-01-17         72.0
15  2022-01-24         79.0
16  2022-01-31         75.0
17  2022-02-07        104.0
18  2022-02-14         31.0
19  2022-02-21         31.0
20  2022-02-28         31.0
21  2022-03-07         31.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1060630
        DateID  WeeklySales
0   2021-10-04         49.0
1   2021-10-11         38.0
2   2021-10-18         45.0
3   2021-10-25         39.0
4   2021-11-01         46.0
5   2021-11-08         40.0
6   2021-11-15         34.0
7   2021-11-22         43.0
8   2021-11-29         33.0
9   2021-12-06         25.0
10  2021-12-13         49.0
11  2021-12-20         21.0
12  2021-12-27         33.0
13  2022-01-10         18.0
14  2022-01-17         20.0
15  2022-01-24         24.0
16  2022-01-31         30.0
17  2022-02-07         22.0
18  2022-02-14         18.0
19  2022-02-21         18.0
20  2022-02-28         18.0
21  2022-03-07         18.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
119554
        DateID  WeeklySales
0   2021-10-04        108.0
1   2021-10-11        120.0
2   2021-10-18        110.0
3   2021-10-25        109.0
4   2021-11-01        137.0
5   2021-11-08        127.0
6   2021-11-15        139.0
7   2021-11-22        217.0
8   2021-11-29        166.0
9   2021-12-06        207.0
10  2021-12-13        140.0
11  2021-12-20        184.0
12  2021-12-27        164.0
13  2022-01-10        196.0
14  2022-01-17        196.0
15  2022-01-24        150.0
16  2022-01-31        192.0
17  2022-02-07        140.0
18  2022-02-14        108.0
19  2022-02-21        108.0
20  2022-02-28        108.0
21  2022-03-07        108.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1071115
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11         20.0
2   2021-10-18          4.0
3   2021-10-25         16.0
4   2021-11-01         10.0
5   2021-11-08         13.0
6   2021-11-15         14.0
7   2021-11-22         10.0
8   2021-11-29         15.0
9   2021-12-06          6.0
10  2021-12-13          5.0
11  2021-12-20          1.0
12  2021-12-27         11.0
13  2022-01-10          5.0
14  2022-01-17          4.0
15  2022-01-24         10.0
16  2022-01-31         19.0
17  2022-02-07          9.0
18  2022-02-14          1.0
19  2022-02-21          1.0
20  2022-02-28          1.0
21  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
88450
        DateID  WeeklySales
0   2021-10-04         91.0
1   2021-10-11        139.0
2   2021-10-18         64.0
3   2021-10-25        137.0
4   2021-11-01        142.0
5   2021-11-08        123.0
6   2021-11-15         93.0
7   2021-11-22        115.0
8   2021-11-29         48.0
9   2021-12-06         99.0
10  2021-12-13         61.0
11  2021-12-20        111.0
12  2021-12-27        106.0
13  2022-01-10         85.0
14  2022-01-17         83.0
15  2022-01-24         85.0
16  2022-01-31         74.0
17  2022-02-07         96.0
18  2022-02-14         48.0
19  2022-02-21         48.0
20  2022-02-28         48.0
21  2022-03-07         48.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1032559
        DateID  WeeklySales
0   2021-10-04         17.0
1   2021-10-11         18.0
2   2021-10-18          9.0
3   2021-10-25          3.0
4   2021-11-01         12.0
5   2021-11-08         13.0
6   2021-11-15          9.0
7   2021-11-22         10.0
8   2021-11-29         13.0
9   2021-12-06         16.0
10  2021-12-13         25.0
11  2021-12-20         39.0
12  2021-12-27         19.0
13  2022-01-10         27.0
14  2022-01-17         25.0
15  2022-01-24         16.0
16  2022-01-31         22.0
17  2022-02-07         16.0
18  2022-02-14          3.0
19  2022-02-21          3.0
20  2022-02-28          3.0
21  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1101571
        DateID  WeeklySales
0   2021-10-04          7.0
1   2021-10-11         18.0
2   2021-10-18          7.0
3   2021-10-25          6.0
4   2021-11-01          7.0
5   2021-11-08          3.0
6   2021-11-15          8.0
7   2021-11-22          4.0
8   2021-11-29          3.0
9   2021-12-06          2.0
10  2021-12-13          2.0
11  2021-12-20         81.0
12  2021-12-27         88.0
13  2022-01-10         57.0
14  2022-01-17         56.0
15  2022-01-24          8.0
16  2022-01-31          7.0
17  2022-02-07         17.0
18  2022-02-14          2.0
19  2022-02-21          2.0
20  2022-02-28          2.0
21  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
35530
        DateID  WeeklySales
0   2021-10-04         21.0
1   2021-10-11         24.0
2   2021-10-18          7.0
3   2021-10-25         15.0
4   2021-11-01          3.0
5   2021-11-08         18.0
6   2021-11-15          3.0
7   2021-11-22         20.0
8   2021-11-29          6.0
9   2021-12-06         21.0
10  2021-12-13          7.0
11  2021-12-20         16.0
12  2021-12-27          8.0
13  2022-01-10         17.0
14  2022-01-17         10.0
15  2022-01-24         16.0
16  2022-02-07         22.0
17  2022-02-14          3.0
18  2022-02-21          3.0
19  2022-02-28          3.0
20  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1105018
        DateID  WeeklySales
0   2021-10-25          3.0
1   2021-11-01          6.0
2   2021-11-08         11.0
3   2021-11-15          4.0
4   2021-11-22          7.0
5   2021-11-29          8.0
6   2021-12-06          6.0
7   2021-12-13          7.0
8   2021-12-20         10.0
9   2021-12-27         15.0
10  2022-01-10         10.0
11  2022-01-17         10.0
12  2022-01-24         13.0
13  2022-01-31          3.0
14  2022-02-07          6.0
15  2022-02-14          3.0
16  2022-02-21          3.0
17  2022-02-28          3.0
18  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
893824
        DateID  WeeklySales
0   2021-10-11         24.0
1   2021-10-18         23.0
2   2021-10-25        101.0
3   2021-11-01         69.0
4   2021-11-08         66.0
5   2021-11-15         38.0
6   2021-11-22         48.0
7   2021-11-29         50.0
8   2021-12-06         39.0
9   2021-12-13         21.0
10  2021-12-20         24.0
11  2021-12-27         23.0
12  2022-01-10         55.0
13  2022-01-17         29.0
14  2022-01-24         63.0
15  2022-01-31         24.0
16  2022-02-07         27.0
17  2022-02-14         21.0
18  2022-02-21         21.0
19  2022-02-28         21.0
20  2022-03-07         21.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1082743
        DateID  WeeklySales
0   2021-10-04          6.0
1   2021-10-11         12.0
2   2021-10-18          4.0
3   2021-10-25          4.0
4   2021-11-01          2.0
5   2021-11-08          9.0
6   2021-11-15         12.0
7   2021-11-22          8.0
8   2021-11-29         16.0
9   2021-12-06         13.0
10  2021-12-13          9.0
11  2021-12-20         15.0
12  2021-12-27         24.0
13  2022-01-10          9.0
14  2022-01-17         75.0
15  2022-01-24         60.0
16  2022-02-07         83.0
17  2022-02-28          2.0
18  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
731104
        DateID  WeeklySales
0   2021-10-04         25.0
1   2021-10-11         14.0
2   2021-10-18          9.0
3   2021-10-25         12.0
4   2021-11-01         23.0
5   2021-11-08         10.0
6   2021-11-15         29.0
7   2021-11-22          7.0
8   2021-11-29         27.0
9   2021-12-06          9.0
10  2021-12-13         23.0
11  2021-12-20         19.0
12  2021-12-27         28.0
13  2022-01-10         10.0
14  2022-01-17         10.0
15  2022-01-31         24.0
16  2022-02-14          7.0
17  2022-02-21          7.0
18  2022-02-28          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
145330
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11         20.0
2   2021-10-18          6.0
3   2021-10-25          9.0
4   2021-11-01          3.0
5   2021-11-08          8.0
6   2021-11-15         10.0
7   2021-11-22          9.0
8   2021-11-29         21.0
9   2021-12-06         15.0
10  2021-12-13         20.0
11  2021-12-20         24.0
12  2021-12-27         15.0
13  2022-01-10          9.0
14  2022-01-17         14.0
15  2022-01-24         16.0
16  2022-01-31         10.0
17  2022-02-07         11.0
18  2022-02-14          3.0
19  2022-02-21          3.0
20  2022-02-28          3.0
21  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
9925
        DateID  WeeklySales
0   2021-10-04          9.0
1   2021-10-11         11.0
2   2021-10-18         13.0
3   2021-10-25          5.0
4   2021-11-01         11.0
5   2021-11-08         11.0
6   2021-11-15         13.0
7   2021-11-22         12.0
8   2021-11-29         10.0
9   2021-12-06         21.0
10  2021-12-13         15.0
11  2021-12-20         17.0
12  2021-12-27         19.0
13  2022-01-10          9.0
14  2022-01-17         14.0
15  2022-01-24         10.0
16  2022-01-31          8.0
17  2022-02-07         21.0
18  2022-02-14          5.0
19  2022-02-21          5.0
20  2022-02-28          5.0
21  2022-03-07          5.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1081060
        DateID  WeeklySales
0   2021-10-04         83.0
1   2021-10-11         62.0
2   2021-10-18         62.0
3   2021-10-25         32.0
4   2021-11-01         84.0
5   2021-11-08         96.0
6   2021-11-15         81.0
7   2021-11-22         93.0
8   2021-11-29         67.0
9   2021-12-06         36.0
10  2021-12-13         49.0
11  2021-12-20         40.0
12  2021-12-27         30.0
13  2022-01-10         16.0
14  2022-01-17         38.0
15  2022-01-24         46.0
16  2022-01-31         23.0
17  2022-02-07         25.0
18  2022-02-14         16.0
19  2022-02-21         16.0
20  2022-02-28         16.0
21  2022-03-07         16.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
216151
        DateID  WeeklySales
0   2021-10-04         12.0
1   2021-10-11         20.0
2   2021-10-18         18.0
3   2021-10-25         12.0
4   2021-11-01          9.0
5   2021-11-08         30.0
6   2021-11-15         19.0
7   2021-11-22         15.0
8   2021-11-29         14.0
9   2021-12-06         19.0
10  2021-12-13         14.0
11  2021-12-20         17.0
12  2021-12-27         16.0
13  2022-01-10         23.0
14  2022-01-17         18.0
15  2022-01-24         20.0
16  2022-01-31         14.0
17  2022-02-07         13.0
18  2022-02-14          9.0
19  2022-02-21          9.0
20  2022-02-28          9.0
21  2022-03-07          9.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1101562
        DateID  WeeklySales
0   2021-10-04          9.0
1   2021-10-11          8.0
2   2021-10-18         10.0
3   2021-10-25         19.0
4   2021-11-01          4.0
5   2021-11-08         13.0
6   2021-11-15          9.0
7   2021-11-22         10.0
8   2021-12-06          7.0
9   2021-12-13         27.0
10  2021-12-20         31.0
11  2021-12-27         12.0
12  2022-01-10         14.0
13  2022-01-17         13.0
14  2022-01-24          2.0
15  2022-01-31          6.0
16  2022-02-07          7.0
17  2022-02-14          2.0
18  2022-02-21          2.0
19  2022-02-28          2.0
20  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1085749
        DateID  WeeklySales
0   2021-10-04          2.0
1   2021-10-11          8.0
2   2021-10-18         14.0
3   2021-10-25          9.0
4   2021-11-01          7.0
5   2021-11-08          2.0
6   2021-11-15          9.0
7   2021-11-22         10.0
8   2021-11-29          9.0
9   2021-12-06          5.0
10  2021-12-13         25.0
11  2021-12-20         16.0
12  2021-12-27          8.0
13  2022-01-10         17.0
14  2022-01-17         14.0
15  2022-01-24         11.0
16  2022-01-31         22.0
17  2022-02-07         12.0
18  2022-02-14          2.0
19  2022-02-21          2.0
20  2022-02-28          2.0
21  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1067128
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11          8.0
2   2021-10-18         17.0
3   2021-10-25         13.0
4   2021-11-01          3.0
5   2021-11-08          5.0
6   2021-11-15          5.0
7   2021-11-22          3.0
8   2021-11-29          8.0
9   2021-12-06          7.0
10  2021-12-13         10.0
11  2021-12-20         10.0
12  2021-12-27         24.0
13  2022-01-10          7.0
14  2022-01-17         12.0
15  2022-01-24          9.0
16  2022-01-31         12.0
17  2022-02-07         10.0
18  2022-02-14          3.0
19  2022-02-21          3.0
20  2022-02-28          3.0
21  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1032568
        DateID  WeeklySales
0   2021-10-04         10.0
1   2021-10-11         10.0
2   2021-10-18          4.0
3   2021-10-25         11.0
4   2021-11-01          8.0
5   2021-11-08          7.0
6   2021-11-15         10.0
7   2021-11-22          6.0
8   2021-11-29         10.0
9   2021-12-06          6.0
10  2021-12-13          4.0
11  2021-12-20         10.0
12  2021-12-27          9.0
13  2022-01-10         17.0
14  2022-01-17         10.0
15  2022-01-24          8.0
16  2022-01-31          6.0
17  2022-02-07          3.0
18  2022-02-14          3.0
19  2022-02-21          3.0
20  2022-02-28          3.0
21  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1049776
        DateID  WeeklySales
0   2021-10-04         15.0
1   2021-10-11         10.0
2   2021-10-18         12.0
3   2021-10-25         16.0
4   2021-11-01         12.0
5   2021-11-08         18.0
6   2021-11-15         17.0
7   2021-11-22         28.0
8   2021-11-29         35.0
9   2021-12-06         35.0
10  2021-12-13         42.0
11  2021-12-20         51.0
12  2021-12-27         19.0
13  2022-01-10         18.0
14  2022-01-17         34.0
15  2022-01-24         32.0
16  2022-01-31         29.0
17  2022-02-07         27.0
18  2022-02-14         10.0
19  2022-02-21         10.0
20  2022-02-28         10.0
21  2022-03-07         10.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1105027
        DateID  WeeklySales
0   2021-10-25          3.0
1   2021-11-01         11.0
2   2021-11-08         10.0
3   2021-11-15          7.0
4   2021-11-22         16.0
5   2021-11-29         13.0
6   2021-12-06         10.0
7   2021-12-13         12.0
8   2021-12-20          7.0
9   2021-12-27         12.0
10  2022-01-10          6.0
11  2022-01-17          5.0
12  2022-01-24          8.0
13  2022-01-31          7.0
14  2022-02-07         14.0
15  2022-02-14          3.0
16  2022-02-21          3.0
17  2022-02-28          3.0
18  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
906595
        DateID  WeeklySales
0   2021-10-04          5.0
1   2021-10-11         11.0
2   2021-10-18          6.0
3   2021-11-01          7.0
4   2021-11-08         10.0
5   2021-11-15         10.0
6   2021-11-22          9.0
7   2021-11-29          9.0
8   2021-12-06          7.0
9   2021-12-13         11.0
10  2021-12-20         17.0
11  2021-12-27         15.0
12  2022-01-10          9.0
13  2022-01-17          7.0
14  2022-01-24         13.0
15  2022-01-31         14.0
16  2022-02-07          7.0
17  2022-02-14          5.0
18  2022-02-21          5.0
19  2022-02-28          5.0
20  2022-03-07          5.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
903976
        DateID  WeeklySales
0   2021-10-04          7.0
1   2021-10-18         11.0
2   2021-10-25         28.0
3   2021-11-01         16.0
4   2021-11-08         20.0
5   2021-11-15         28.0
6   2021-11-22         25.0
7   2021-11-29         33.0
8   2021-12-06         19.0
9   2021-12-13         21.0
10  2021-12-20          8.0
11  2021-12-27         19.0
12  2022-01-10         22.0
13  2022-01-17         34.0
14  2022-01-24         19.0
15  2022-01-31         33.0
16  2022-02-07         31.0
17  2022-02-14          7.0
18  2022-02-21          7.0
19  2022-02-28          7.0
20  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1081069
        DateID  WeeklySales
0   2021-10-04         14.0
1   2021-10-11         26.0
2   2021-10-18         12.0
3   2021-10-25          8.0
4   2021-11-01         17.0
5   2021-11-08         19.0
6   2021-11-15         18.0
7   2021-11-22          8.0
8   2021-11-29         15.0
9   2021-12-06         14.0
10  2021-12-13         13.0
11  2021-12-20         15.0
12  2021-12-27         13.0
13  2022-01-10         10.0
14  2022-01-17         21.0
15  2022-01-24         24.0
16  2022-01-31         17.0
17  2022-02-07          9.0
18  2022-02-14          8.0
19  2022-02-21          8.0
20  2022-02-28          8.0
21  2022-03-07          8.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1070818
        DateID  WeeklySales
0   2021-10-04          8.0
1   2021-10-11          4.0
2   2021-10-18         16.0
3   2021-10-25         12.0
4   2021-11-01         15.0
5   2021-11-08          9.0
6   2021-11-15         16.0
7   2021-11-22         19.0
8   2021-11-29          7.0
9   2021-12-06          4.0
10  2021-12-13          6.0
11  2021-12-20         10.0
12  2021-12-27         18.0
13  2022-01-10          1.0
14  2022-01-17         11.0
15  2022-01-24          6.0
16  2022-01-31          8.0
17  2022-02-07          5.0
18  2022-02-14          1.0
19  2022-02-21          1.0
20  2022-02-28          1.0
21  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1063600
        DateID  WeeklySales
0   2021-10-04         10.0
1   2021-10-11         14.0
2   2021-10-18          4.0
3   2021-10-25         14.0
4   2021-11-01          7.0
5   2021-11-08         11.0
6   2021-11-15          8.0
7   2021-11-22         17.0
8   2021-11-29          7.0
9   2021-12-06          9.0
10  2021-12-13          9.0
11  2021-12-20         14.0
12  2021-12-27          9.0
13  2022-01-10          8.0
14  2022-01-17         18.0
15  2022-01-24         13.0
16  2022-01-31          5.0
17  2022-02-07         10.0
18  2022-02-14          4.0
19  2022-02-21          4.0
20  2022-02-28          4.0
21  2022-03-07          4.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
872260
        DateID  WeeklySales
0   2021-10-04         17.0
1   2021-10-11         11.0
2   2021-10-18         22.0
3   2021-10-25         15.0
4   2021-11-01         11.0
5   2021-11-08         10.0
6   2021-11-15          7.0
7   2021-11-22         15.0
8   2021-11-29          4.0
9   2021-12-06         17.0
10  2021-12-13         14.0
11  2021-12-20         11.0
12  2021-12-27         21.0
13  2022-01-10         36.0
14  2022-01-17         10.0
15  2022-01-24         11.0
16  2022-01-31          4.0
17  2022-02-07         12.0
18  2022-02-14          4.0
19  2022-02-21          4.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
43738
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11         13.0
2   2021-10-18          8.0
3   2021-10-25         13.0
4   2021-11-01          5.0
5   2021-11-08         11.0
6   2021-11-15         12.0
7   2021-11-22         27.0
8   2021-11-29         17.0
9   2021-12-06         19.0
10  2021-12-13         18.0
11  2021-12-20         24.0
12  2021-12-27         12.0
13  2022-01-10         30.0
14  2022-01-17         28.0
15  2022-01-24         17.0
16  2022-01-31         17.0
17  2022-02-07         31.0
18  2022-02-14          5.0
19  2022-02-21          5.0
20  2022-02-28          5.0
21  2022-03-07          5.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
687616
        DateID  WeeklySales
0   2021-10-04         15.0
1   2021-10-11         10.0
2   2021-11-08          7.0
3   2021-11-15         10.0
4   2021-11-22         22.0
5   2021-11-29         19.0
6   2021-12-06         23.0
7   2021-12-13         23.0
8   2021-12-20         25.0
9   2021-12-27         15.0
10  2022-01-10         15.0
11  2022-01-17          9.0
12  2022-01-24         13.0
13  2022-01-31         18.0
14  2022-02-07         14.0
15  2022-02-14          7.0
16  2022-02-21          7.0
17  2022-02-28          7.0
18  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1081321
        DateID  WeeklySales
0   2021-10-04         27.0
1   2021-10-11         26.0
2   2021-10-18         19.0
3   2021-10-25          7.0
4   2021-11-01         17.0
5   2021-11-08         18.0
6   2021-11-15          9.0
7   2021-11-22         16.0
8   2021-11-29         12.0
9   2021-12-06         20.0
10  2021-12-13         15.0
11  2021-12-20         26.0
12  2021-12-27         18.0
13  2022-01-10         22.0
14  2022-01-17          2.0
15  2022-02-07          6.0
16  2022-02-14          2.0
17  2022-02-21          2.0
18  2022-02-28          2.0
19  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
38518
        DateID  WeeklySales
0   2021-10-04         25.0
1   2021-10-11         13.0
2   2021-10-18         19.0
3   2021-10-25          9.0
4   2021-11-01          6.0
5   2021-11-08          8.0
6   2021-11-15         12.0
7   2021-11-22         18.0
8   2021-11-29         14.0
9   2021-12-06         28.0
10  2021-12-13         16.0
11  2021-12-20         12.0
12  2021-12-27         18.0
13  2022-01-10         17.0
14  2022-01-17         12.0
15  2022-01-24         18.0
16  2022-01-31         17.0
17  2022-02-07         35.0
18  2022-02-14          6.0
19  2022-02-21          6.0
20  2022-02-28          6.0
21  2022-03-07          6.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
37861
        DateID  WeeklySales
0   2021-10-04        168.0
1   2021-10-11         89.0
2   2021-10-18         78.0
3   2021-10-25        125.0
4   2021-11-01        143.0
5   2021-11-08         80.0
6   2021-11-15         83.0
7   2021-11-22        143.0
8   2021-11-29        131.0
9   2021-12-06        127.0
10  2021-12-13         91.0
11  2021-12-20        143.0
12  2021-12-27        110.0
13  2022-01-10        144.0
14  2022-01-17        126.0
15  2022-01-24        165.0
16  2022-01-31        241.0
17  2022-02-07        239.0
18  2022-02-14         78.0
19  2022-02-21         78.0
20  2022-02-28         78.0
21  2022-03-07         78.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1081078
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11          6.0
2   2021-10-18         12.0
3   2021-10-25         17.0
4   2021-11-01         19.0
5   2021-11-08          8.0
6   2021-11-15         22.0
7   2021-11-22          3.0
8   2021-11-29         21.0
9   2021-12-06         21.0
10  2021-12-13          8.0
11  2021-12-20         13.0
12  2021-12-27         11.0
13  2022-01-10         15.0
14  2022-01-17         11.0
15  2022-01-24          5.0
16  2022-01-31          2.0
17  2022-02-07         11.0
18  2022-02-14          2.0
19  2022-02-21          2.0
20  2022-02-28          2.0
21  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
65788
        DateID  WeeklySales
0   2021-10-04         46.0
1   2021-10-11         54.0
2   2021-10-18         52.0
3   2021-10-25         32.0
4   2021-11-01          4.0
5   2021-11-08         12.0
6   2021-11-15          8.0
7   2021-11-22         10.0
8   2021-11-29         15.0
9   2021-12-06         13.0
10  2021-12-13         11.0
11  2021-12-20          7.0
12  2021-12-27         14.0
13  2022-01-10          8.0
14  2022-01-17          9.0
15  2022-01-24         17.0
16  2022-01-31          9.0
17  2022-02-07          9.0
18  2022-02-14          4.0
19  2022-02-21          4.0
20  2022-02-28          4.0
21  2022-03-07          4.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1003183
        DateID  WeeklySales
0   2021-10-04         18.0
1   2021-10-11         20.0
2   2021-10-18         19.0
3   2021-10-25         11.0
4   2021-11-01          4.0
5   2021-11-08         15.0
6   2021-11-15          6.0
7   2021-11-22         30.0
8   2021-11-29          6.0
9   2021-12-06         15.0
10  2021-12-13          6.0
11  2021-12-20          2.0
12  2021-12-27         20.0
13  2022-01-10         11.0
14  2022-01-17         31.0
15  2022-01-24         50.0
16  2022-01-31         19.0
17  2022-02-07         37.0
18  2022-02-14          2.0
19  2022-02-21          2.0
20  2022-02-28          2.0
21  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
35449
        DateID  WeeklySales
0   2021-10-04          1.0
1   2021-10-11          3.0
2   2021-10-18          6.0
3   2021-10-25          6.0
4   2021-11-01          5.0
5   2021-11-08          7.0
6   2021-11-15          5.0
7   2021-11-22         18.0
8   2021-11-29         11.0
9   2021-12-06         27.0
10  2021-12-13         17.0
11  2021-12-20         20.0
12  2021-12-27          1.0
13  2022-01-10         15.0
14  2022-01-17         11.0
15  2022-01-24         16.0
16  2022-01-31         23.0
17  2022-02-07         29.0
18  2022-02-14          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1068883
        DateID  WeeklySales
0   2021-10-04          3.0
1   2021-10-11          3.0
2   2021-10-18          1.0
3   2021-10-25          1.0
4   2021-11-01          5.0
5   2021-11-08          3.0
6   2021-11-15          4.0
7   2021-11-22          4.0
8   2021-11-29          9.0
9   2021-12-06          9.0
10  2021-12-13          4.0
11  2021-12-20          6.0
12  2021-12-27          7.0
13  2022-01-10          1.0
14  2022-01-17          2.0
15  2022-01-24         10.0
16  2022-01-31          8.0
17  2022-02-07         11.0
18  2022-02-14          1.0
19  2022-02-21          1.0
20  2022-02-28          1.0
21  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1081339
        DateID  WeeklySales
0   2021-10-04         20.0
1   2021-10-18          3.0
2   2021-10-25         23.0
3   2021-11-01          9.0
4   2021-11-08         29.0
5   2021-11-15         14.0
6   2021-11-22         18.0
7   2021-11-29         14.0
8   2021-12-06         15.0
9   2021-12-13         32.0
10  2021-12-20         36.0
11  2021-12-27         19.0
12  2022-01-10          3.0
13  2022-01-17          4.0
14  2022-02-07          3.0
15  2022-02-14          3.0
16  2022-02-21          3.0
17  2022-02-28          3.0
18  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1101553
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11         10.0
2   2021-10-18          5.0
3   2021-10-25          3.0
4   2021-11-01          5.0
5   2021-11-08          9.0
6   2021-11-15          5.0
7   2021-11-22          6.0
8   2021-11-29          3.0
9   2021-12-06         16.0
10  2021-12-13         17.0
11  2021-12-20          5.0
12  2021-12-27          6.0
13  2022-01-10          8.0
14  2022-01-17          2.0
15  2022-01-24          1.0
16  2022-01-31          5.0
17  2022-02-07          1.0
18  2022-02-21          1.0
19  2022-02-28          1.0
20  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
132334
        DateID  WeeklySales
0   2021-10-04         14.0
1   2021-10-11         20.0
2   2021-10-18         11.0
3   2021-10-25          7.0
4   2021-11-01         12.0
5   2021-11-08         20.0
6   2021-11-15         19.0
7   2021-11-22         42.0
8   2021-11-29         44.0
9   2021-12-06         34.0
10  2021-12-13         31.0
11  2021-12-20         25.0
12  2021-12-27         37.0
13  2022-01-10         22.0
14  2022-01-17         23.0
15  2022-01-24         16.0
16  2022-01-31         15.0
17  2022-02-07         13.0
18  2022-02-14          7.0
19  2022-02-21          7.0
20  2022-02-28          7.0
21  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
858886
        DateID  WeeklySales
0   2021-10-04         10.0
1   2021-10-11         16.0
2   2021-10-18          7.0
3   2021-10-25         14.0
4   2021-11-01          9.0
5   2021-11-08          4.0
6   2021-11-15          8.0
7   2021-11-22          8.0
8   2021-11-29         19.0
9   2021-12-06          3.0
10  2021-12-13         11.0
11  2021-12-20         11.0
12  2021-12-27          5.0
13  2022-01-10         10.0
14  2022-01-17         18.0
15  2022-01-24          6.0
16  2022-01-31          9.0
17  2022-02-07          9.0
18  2022-02-14          3.0
19  2022-02-21          3.0
20  2022-02-28          3.0
21  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
111436
        DateID  WeeklySales
0   2021-10-04          6.0
1   2021-10-11         11.0
2   2021-10-18          6.0
3   2021-10-25          6.0
4   2021-11-01          2.0
5   2021-11-08          5.0
6   2021-11-15          4.0
7   2021-11-22          8.0
8   2021-11-29         20.0
9   2021-12-06         14.0
10  2021-12-13         14.0
11  2021-12-20          8.0
12  2021-12-27         19.0
13  2022-01-10         13.0
14  2022-01-17         17.0
15  2022-01-24          7.0
16  2022-01-31          9.0
17  2022-02-07          9.0
18  2022-02-14          2.0
19  2022-02-21          2.0
20  2022-02-28          2.0
21  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
111382
        DateID  WeeklySales
0   2021-10-04         24.0
1   2021-10-11         21.0
2   2021-10-18         11.0
3   2021-10-25         18.0
4   2021-11-01         11.0
5   2021-11-08         15.0
6   2021-11-15         10.0
7   2021-11-22         16.0
8   2021-11-29         16.0
9   2021-12-06         15.0
10  2021-12-13          7.0
11  2021-12-20          7.0
12  2021-12-27         18.0
13  2022-01-10         11.0
14  2022-01-17          9.0
15  2022-01-24         11.0
16  2022-01-31         13.0
17  2022-02-07         10.0
18  2022-02-14          7.0
19  2022-02-21          7.0
20  2022-02-28          7.0
21  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
999403
        DateID  WeeklySales
0   2021-10-04          5.0
1   2021-10-11          5.0
2   2021-10-18          3.0
3   2021-10-25         11.0
4   2021-11-01         14.0
5   2021-11-08         15.0
6   2021-11-15          8.0
7   2021-11-22         10.0
8   2021-11-29          6.0
9   2021-12-06          6.0
10  2021-12-13         18.0
11  2021-12-20         14.0
12  2021-12-27         33.0
13  2022-01-10         13.0
14  2022-01-17         36.0
15  2022-01-24         38.0
16  2022-01-31         16.0
17  2022-02-07         16.0
18  2022-02-14          3.0
19  2022-02-21          3.0
20  2022-02-28          3.0
21  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
225259
        DateID  WeeklySales
0   2021-10-04         17.0
1   2021-10-11         11.0
2   2021-10-18         15.0
3   2021-10-25         11.0
4   2021-11-01          5.0
5   2021-11-08          9.0
6   2021-11-15         10.0
7   2021-11-22         10.0
8   2021-11-29         18.0
9   2021-12-06         15.0
10  2021-12-13         14.0
11  2021-12-20         14.0
12  2021-12-27          9.0
13  2022-01-10         20.0
14  2022-01-17         14.0
15  2022-01-24          5.0
16  2022-01-31         23.0
17  2022-02-07         14.0
18  2022-02-14          5.0
19  2022-02-21          5.0
20  2022-02-28          5.0
21  2022-03-07          5.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
213802
        DateID  WeeklySales
0   2021-10-04         11.0
1   2021-10-11         14.0
2   2021-10-18         11.0
3   2021-10-25          8.0
4   2021-11-01          6.0
5   2021-11-08          6.0
6   2021-11-15          3.0
7   2021-11-22          7.0
8   2021-11-29         15.0
9   2021-12-06         11.0
10  2021-12-13          9.0
11  2021-12-20          9.0
12  2021-12-27          4.0
13  2022-01-10          9.0
14  2022-01-17          7.0
15  2022-01-24          9.0
16  2022-01-31         17.0
17  2022-02-07          7.0
18  2022-02-14          3.0
19  2022-02-21          3.0
20  2022-02-28          3.0
21  2022-03-07          3.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1092184
        DateID  WeeklySales
0   2021-10-04         15.0
1   2021-10-11         16.0
2   2021-10-18         12.0
3   2021-10-25         25.0
4   2021-11-01         16.0
5   2021-11-08          8.0
6   2021-11-15         10.0
7   2021-11-22         14.0
8   2021-11-29         38.0
9   2021-12-06         23.0
10  2021-12-13         10.0
11  2021-12-20         28.0
12  2021-12-27         30.0
13  2022-01-10         20.0
14  2022-01-17         19.0
15  2022-01-24         21.0
16  2022-01-31         28.0
17  2022-02-07         22.0
18  2022-02-14          8.0
19  2022-02-21          8.0
20  2022-02-28          8.0
21  2022-03-07          8.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1076929
        DateID  WeeklySales
0   2021-10-04          4.0
1   2021-10-11          7.0
2   2021-10-18          6.0
3   2021-10-25          3.0
4   2021-11-01          5.0
5   2021-11-08          5.0
6   2021-11-15          5.0
7   2021-11-22          2.0
8   2021-11-29          1.0
9   2021-12-06          3.0
10  2021-12-13          8.0
11  2021-12-20         59.0
12  2021-12-27         63.0
13  2022-01-10          3.0
14  2022-01-17          7.0
15  2022-01-24         10.0
16  2022-01-31          6.0
17  2022-02-07          6.0
18  2022-02-14          1.0
19  2022-02-21          1.0
20  2022-02-28          1.0
21  2022-03-07          1.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1006099
        DateID  WeeklySales
0   2021-10-04          3.0
1   2021-10-11          3.0
2   2021-10-18          4.0
3   2021-10-25          5.0
4   2021-11-01          4.0
5   2021-11-08         21.0
6   2021-11-15          2.0
7   2021-11-22          6.0
8   2021-11-29          2.0
9   2021-12-06          8.0
10  2021-12-13          4.0
11  2021-12-20          5.0
12  2021-12-27          4.0
13  2022-01-10         14.0
14  2022-01-17         23.0
15  2022-01-24         11.0
16  2022-01-31         24.0
17  2022-02-07         13.0
18  2022-02-14          2.0
19  2022-02-21          2.0
20  2022-02-28          2.0
21  2022-03-07          2.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running
1077118
        DateID  WeeklySales
0   2021-10-04         10.0
1   2021-10-11          7.0
2   2021-12-06         10.0
3   2021-12-13         24.0
4   2021-12-20         17.0
5   2021-12-27         17.0
6   2022-01-10         18.0
7   2022-01-17         28.0
8   2022-01-24         34.0
9   2022-01-31         46.0
10  2022-02-07         13.0
11  2022-02-14          7.0
12  2022-02-21          7.0
13  2022-02-28          7.0
14  2022-03-07          7.0

C:\Users\Vipooshan\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:49: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

week cal running

In [76]:
df_prediction

    CategoryCode ItemCode Week PredictedSales
0     category_2   117610   w1             15
1     category_2   117610   w2             11
2     category_2   117610   w3             11
3     category_2   117610   w4             11
4     category_1   370195   w1            113
..           ...      ...  ...            ...
383   category_2  1006099   w4             16
384   category_1  1077118   w1             26
385   category_1  1077118   w2             20
386   category_1  1077118   w3             20
387   category_1  1077118   w4             20

[388 rows x 4 columns]

In [77]:
merged_result = pd.merge(test, df_prediction, on=['CategoryCode','ItemCode', 'Week'], how='left')
merged_result

    CategoryCode ItemCode Week  PredictedSales_x      DateID PredictedSales_y
0     category_1    43738   w4               NaN  2022-03-07               28
1     category_2  1006090   w1               NaN  2022-02-14               46
2     category_2  1076929   w4               NaN  2022-03-07               38
3     category_1  1081321   w3               NaN  2022-02-28               16
4     category_2   216151   w4               NaN  2022-03-07               29
..           ...      ...  ...               ...         ...              ...
372   category_2  1101571   w1               NaN  2022-02-14              121
373   category_2  1090258   w4               NaN  2022-03-07               28
374   category_2   906595   w1               NaN  2022-02-14               17
375   category_2    32245   w1               NaN  2022-02-14               95
376   category_2  1006090   w2               NaN  2022-02-21               35

[377 rows x 6 columns]

In [78]:
merged_result.drop(columns='PredictedSales_x', inplace=True)

In [79]:
merged_result.rename(columns={'PredictedSales_y':'PredictedSales'}, inplace=True)

In [80]:
merged_result[merged_result.isnull().any(axis=1)]

Empty DataFrame
Columns: [CategoryCode, ItemCode, Week, DateID, PredictedSales]
Index: []

In [81]:
# merged_result['PredictedSales'] = round(merged_result['PredictedSales'])
# merged_result['PredictedSales'] = merged_result['PredictedSales'].astype(int)

In [82]:
merged_result.head()

  CategoryCode ItemCode Week      DateID PredictedSales
0   category_1    43738   w4  2022-03-07             28
1   category_2  1006090   w1  2022-02-14             46
2   category_2  1076929   w4  2022-03-07             38
3   category_1  1081321   w3  2022-02-28             16
4   category_2   216151   w4  2022-03-07             29

In [83]:
train_for_test.sort_values(by='WeeklySales', ascending=False).head(20)

          DateID CategoryCode  ItemCode  Month  Day Week  WeeklySales
1109  2021-10-18   category_3    169504     10   23  w03          808
2255  2021-10-04   category_3    169504     10    8  w01          780
2727  2021-12-13   category_3    169504     12   17  w11          737
3405  2021-12-27   category_4    123307     12   30  w13          731
87    2021-11-15   category_3    169504     11   17  w07          720
480   2021-12-06   category_3    169504     12    7  w10          697
152   2022-01-24   category_3    169504      1   24  w17          689
598   2021-11-08   category_3    169504     11   12  w06          686
941   2021-10-25   category_3    169504     10   30  w04          685
3610  2021-12-20   category_4    123307     12   24  w12          683
1601  2021-11-22   category_3    169504     11   23  w08          676
799   2021-11-01   category_3    169504     11    6  w05          664
3026  2021-12-27   category_3    169504     12   30  w13          662
4514  2021-11-29   category_3    169504     12    3  w09          604
1726  2021-10-04   category_4    123307     10    8  w01          569
67    2022-02-07   category_4    123307      2    9  w19          555
922   2021-10-25   category_4    123307     10   30  w04          552
4885  2022-01-10   category_4    123307      1   13  w15          539
3172  2021-12-20   category_3    169504     12   26  w12          534
3589  2022-01-17   category_4    123307      1   22  w16          527

In [84]:
merged_result.sort_values(by=['PredictedSales'], ascending=False).head(7)

    CategoryCode ItemCode Week      DateID PredictedSales
12    category_4   123307   w1  2022-02-14           1103
322   category_4   123307   w2  2022-02-21            935
284   category_3   169504   w1  2022-02-14            907
288   category_4   123307   w3  2022-02-28            902
161   category_4   123307   w4  2022-03-07            873
39    category_3   169504   w4  2022-03-07            807
107   category_3   169504   w3  2022-02-28            806

In [85]:
# max_index = merged_result.sort_values(by=['PredictedSales'], ascending=False).head(7).index

In [86]:
# merged_result['PredictedSales'].iloc[max_index] =  merged_result['PredictedSales'].iloc[max_index].values - 400

In [87]:
# merged_result['PredictedSales'].iloc[39] = merged_result['PredictedSales'].iloc[39] - 400
# merged_result['PredictedSales'].iloc[39] = merged_result['PredictedSales'].iloc[39] - 400

In [88]:
merged_result.sort_values(by=['PredictedSales'], ascending=True).head(7)

    CategoryCode ItemCode Week      DateID PredictedSales
147   category_2  1101571   w4  2022-03-07              5
38    category_1  1075651   w2  2022-02-21              5
127   category_2  1101553   w4  2022-03-07              6
43    category_2    57058   w3  2022-02-28              6
275   category_1  1081321   w2  2022-02-21              6
246   category_1  1068883   w4  2022-03-07              6
71    category_1  1068883   w2  2022-02-21              7

In [106]:
submission = pd.DataFrame()
submission['ID'] = merged_result['CategoryCode'] + '_' + merged_result['ItemCode'].astype(str) + '_' + merged_result['Week']
submission['WeeklySales'] = merged_result['PredictedSales']

In [107]:
submission.head()

                      ID WeeklySales
0    category_1_43738_w4          39
1  category_2_1006090_w1          47
2  category_2_1076929_w4          39
3  category_1_1081321_w3          29
4   category_2_216151_w4          34

In [108]:
# from google.colab import files
submission.to_csv('lstm_submission2.csv', index=False) 
# files.download('new_submission.csv')

In [ ]:
df_prediction

In [ ]:
merged_result_sor_gr = merged_result.sort_values(by=['Week', 'ItemCode']).reset_index(drop=True)

In [ ]:
merged_result_sor_gr

In [ ]:
plt.figure(figsize=(20, 10))
plt.plot(merged_result_sor_gr.index, merged_result_sor_gr['PredictedSales'])
plt.legend('PredictedSales')
cat_labels = merged_result_sor_gr['CategoryCode'].values
week_labels = merged_result_sor_gr['Week'].values
# plt.xticks(cat_labels, week_labels)
# plt.xlabel(sorted_merged_train['WeeklySales'].name)
plt.show()

In [ ]:
plt.figure(figsize=(20, 10))
plt.plot(val_sor_gr.index, val_sor_gr['WeeklySales'])
plt.plot(merged_result_sor_gr.index, merged_result_sor_gr['PredictedSales'])

plt.legend(['ValidationSales', 'PredictedTestSales'])
cat_labels = merged_result_sor_gr['CategoryCode'].values
week_labels = merged_result_sor_gr['Week'].values
# plt.xticks(cat_labels, week_labels)
# plt.xlabel(sorted_merged_train['WeeklySales'].name)
plt.show()

In [ ]:
val_sor_gr = validation.sort_values(by=['Week', 'ItemCode']).reset_index(drop=True)

In [ ]:
plt.figure(figsize=(20, 10))
plt.plot(val_sor_gr.index, val_sor_gr['WeeklySales'])
plt.legend('WeeklySales')
cat_labels = val_sor_gr['CategoryCode'].values
week_labels = val_sor_gr['Week'].values
# plt.xticks(cat_labels, week_labels)
# plt.xlabel(sorted_merged_train['WeeklySales'].name)
plt.show()

In [ ]:
sorted_trainv = train.sort_values(by=['ItemCode', 'DateID'], ascending=True)
week_sale_grouped_trainv = sorted_trainv.groupby(['ItemCode','Week'])['DailySales'].sum()
merged_trainv = pd.merge(train[['DateID','CategoryCode','ItemCode','Month','Day','Week']], week_sale_grouped_trainv, on=['ItemCode','Week'], how='left')

In [ ]:
merged_trainv = merged_trainv.drop_duplicates(subset=['CategoryCode','ItemCode', 'Week'])
merged_trainv.rename(columns={'DailySales':'WeeklySales'}, inplace=True)
sorted_merged_trainv_for_valid = merged_trainv.sort_values(by=['Week', 'CategoryCode', 'ItemCode'], ascending=True)

In [ ]:
sorted_merged_train.head(30)

In [ ]:
#merge with actual sales dataframe
item_pred = pd.merge(item,df_result,on='DateID',how='left')

In [ ]:
train_test_merged[train_test_merged['ItemCode'] == 1061341]

In [ ]:
result = item_pred.dropna()
result

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(result['WeeklySales'].values, result['pred_value'].values)

In [ ]:
val = item_pred.dropna()['WeeklySales'].values
pred = item_pred.dropna()['pred_value'].values

In [109]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error([-14], [20])

2.4285714285714284

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
pred_df = pd.DataFrame(columns=['Actual', 'Prediction'])
pred_df['Actual'] = Y_valid
pred_df['Prediction'] = pred

In [ ]:
pred_df